### ISSUE TITLE
classifier syntax in deps.edn

### ISSUE THREAD

**Issue by puredanger** [cljfx/cljfx#1]
Hi, just wanted to let you know that the classifier syntax in deps.edn has changed in the latest release of clj (1.10.0.408). In your case, it looks like you don't actually even need the classifiers at all. The openjfx artifacts depend on the correct platform-specific (based on the caller's platform) classifier version of the artifact.
The latest release of deps.edn addresses many issues with classifiers and will correctly pull in those deps now. So, I believe all you need to do to work with the latest version is to simply remove all of the :classifier attributes from your deps.edn.
If you have any issues, please file a ticket at https://dev.clojure.org/jira/browse/TDEPS for tools.deps.alpha.

**Comment by vlaaad** [comment]
Yes, I no longer need classifiers at all, thank you!
