### ISSUE TITLE
how to access the stage instance?

### ISSUE THREAD

**Issue by torkus** [cljfx/cljfx#101]
I need to access the javafx `Stage` instance, or at least the root component of the `Scene`.

I'm using a cljfx configuration very similar to the example in the [README](https://github.com/cljfx/cljfx#atoms), with the stage, scene and root descriptions inside a function that is called when the state changes.

**Comment by vlaaad** [comment]
Hi @torkus!

Where do you want to access it? In the event handler? Or in some other component?

For event handlers, accessing the stage is possible by getting target's scene's window: `(-> event .getTarget .getScene .getWindow)` (some type hints might be necessary).

**Comment by torkus** [comment]
I have two problems currently and they are not the first problems that could have been solved if I had access to the root so I could traverse the nodes.

First problem is that menu accelerators don't have access to the root node for me to then descend and find the tab-pane to select an index when the menu that the accelerator is attached to hasn't been displayed yet. It's weird enough to be a bug and may possibly be this one: https://bugs.openjdk.java.net/browse/JDK-8094496 (but that would make it *very* old)

The second problem is I want to programmatically navigate the nodes and inspect the values of properties for unit testing and I have no shim to get in there if I'm not using the `fx/instance` and `fx/create-component`.

**Comment by vlaaad** [comment]
Sorry, I couldn't understand your problem given the description. Can describe it in some other way? What is the problem you are trying to solve by accessing the stage instance? Do you want to make a menu item action focus on a particular tab in a tab-pane?

**Comment by torkus** [comment]
Perhaps [some code](https://github.com/ogri-la/strongbox/blob/b32b7841a1c68f623a45de85a7cd828759f11496/src/strongbox/ui/jfx.clj#L348-L355) will help.

Here, a menu item has an accelerator. Under certain conditions the root node cannot be reached in order to then find the tab-pane to switch the selected tab. It could be a bug in Javafx or something I don't understand.

More generally, if I had access to the stage/scene/root node instance I could avoid a class of problems where I travel 'up' the node hierarchy before searching for descendants. Does that make sense? Is it unreasonable to hold on to a reference for this sort of thing?

**Comment by vlaaad** [comment]
I would say your best bet is to make it reactive by:
1. Having currently active tab in the state;
2. Making menu actions change the active tab state;
3. Making cljfx select the tab when the active tab state is changed;
4. Making a user-triggered tab switch to change the active tab state.

Here is an example that uses menu-bar with tab panes:
```clj
(require '[cljfx.api :as fx]
         '[cljfx.ext.tab-pane :as fx.ext.tab-pane])

(def state
  ;; 1. Having currently active tab in the state;
  (atom {:tab :foo}))

(defn view [{:keys [tab]}]
  {:fx/type :stage
   :showing true
   :scene
   {:fx/type :scene
    :root
    {:fx/type :v-box
     :children
     [{:fx/type :menu-bar
       :menus [{:fx/type :menu
                :text "Tabs"
                :items [{:fx/type :menu-item
                         :accelerator [:ctrl :f]
                         ;; 2. Making menu actions change the active tab state;
                         :on-action (fn [_] (swap! state assoc :tab :foo))
                         :text "Select foo"}
                        {:fx/type :menu-item
                         :accelerator [:ctrl :b]
                         ;; 2. Making menu actions change the active tab state;
                         :on-action (fn [_] (swap! state assoc :tab :bar))
                         :text "Select bar"}]}]}
      {:fx/type fx.ext.tab-pane/with-selection-props
       ;; 3. Making cljfx select the tab when the active tab state is changed;
       :props {:selected-index ({:foo 0 :bar 1} tab)}
       :desc {:fx/type :tab-pane
              :tabs [{:fx/type :tab
                      :closable false
                      ;; 4. Making a user-triggered tab switch to change the active tab state.
                      :on-selection-changed #(when (.isSelected ^javafx.scene.control.Tab
                                                                (.getTarget ^javafx.event.Event %))
                                               (swap! state assoc :tab :foo))
                      :text "Foo"
                      :content {:fx/type :label
                                :text "Foo content"}}
                     {:fx/type :tab
                      :closable false
                      ;; 4. Making a user-triggered tab switch to change the active tab state.
                      :on-selection-changed #(when (.isSelected ^javafx.scene.control.Tab 
                                                                (.getTarget ^javafx.event.Event %))
                                               (swap! state assoc :tab :bar))
                      :text "Bar"
                      :content {:fx/type :label
                                :text "Bar content"}}]}}]}}})

(fx/mount-renderer state
  (fx/create-renderer :middleware (fx/wrap-map-desc #'view)))
```

**Comment by vlaaad** [comment]
Feel free to reopen if this didn't help :)

**Comment by torkus** [comment]
First off, thank you for the detailed reply, it's appreciated.

But secondly, it doesn't answer my question - how do I get a hold of a reference to the stage/scene/root node. If CLJS can't manage it because that isn't how it's designed, then that's fine and we can leave the ticket closed.

**Comment by torkus** [comment]
> Feel free to reopen

I don't appear to have any means to re-open an issue.

**Comment by vlaaad** [comment]
Woah, I had no idea people can't reopen their issues :D

I didn't answer your direct question because I focused on solving the problem you are experiencing: it can be solved in various ways, and I find an approach where all mutations are produced from immutable data structures easier to think in, and cljfx was designed for this approach.

Cljfx provides some mechanism to define and pass references to its components using [`fx/ext-let-refs` and `fx/ext-get-ref`](https://github.com/cljfx/cljfx#included-extension-lifecycles), but I'm not sure it will work for what you want because cljfx can't pass those refs to event handlers and it can't express circular references, which seems to be the case here (stage needs menu item that needs stage).

P.S. there is `(javafx.stage.Window/getWindows)` to get all open windows, perhaps you can find your window there. Note that popups and context menus are there as well since in JavaFX terms they are also windows, so you'll need some filtering.

**Comment by torkus** [comment]
> P.S. there is (javafx.stage.Window/getWindows) to get all open windows

This looks like a winner, thanks.
