### ISSUE TITLE
CSS resources cannot be loaded

### ISSUE THREAD

**Issue by jimpil** [cljfx/cljfx#104]
Hi there,

I have a `resources/dark-mode.css` file (I don't think the content is relevant but you can see it [here](https://stackoverflow.com/questions/49159286/make-a-dark-mode-with-javafx)). I am then defining a Var like so:

```clj
(def dark-mode (-> "dark-mode.css"  io/resource .getPath delay)) ;; slurp-ing this works fine
```
and passing it to the scene like so:
```clj
:stylesheets [(deref dark-mode)]
```
However, all I get is `Resource abc/def/dark-mode.css not found`. Am I doing something wrong here?

Many thanks in advance...

**Comment by vlaaad** [comment]
It's probably something like `:stylesheets ["dark-mode.css"]`, see [stylesheets](https://openjfx.io/javadoc/14/javafx.graphics/javafx/scene/Scene.html#getStylesheets()) documentation in JavaFX, `:stylesheets` property translates into something like `scene.getStylesheets().setAll(...)`
