### ISSUE TITLE
why the height and width prop in stage but scene

### ISSUE THREAD

**Issue by LoveLiveSun** [cljfx/cljfx#105]
i just want to know why the width and height prop not like that
`   {:fx/type :stage
     ......
     :scene {:fx/type :scene
                 ......
                 :width 300
                 :height 100
                 ......}}}`
but like that
`   {:fx/type :stage
     ......
     :width 300
     :height 100
     ......
     :scene {:fx/type :scene
                 ......}}`

the first one more closer to the java code

**Comment by vlaaad** [comment]
Hi @LoveLiveSun!

You are asking the wrong person :) 

This isn't my decision, cljfx just provides a data-driven API to JavaFX. JavaFX allows setting width on [Window](https://openjfx.io/javadoc/14/javafx.graphics/javafx/stage/Window.html#setWidth(double)) (a parent class of [Stage](https://openjfx.io/javadoc/14/javafx.graphics/javafx/stage/Stage.html)), but not on [Scene](https://openjfx.io/javadoc/14/javafx.graphics/javafx/scene/Scene.html#widthProperty), where width is read-only. You should ask JavaFX maintainers why they did it that way.
