### ISSUE TITLE
Idiom for long-running tasks

### ISSUE THREAD

**Issue by jimpil** [cljfx/cljfx#106]
It is pretty trivial to create a generic task runner as an effect. For example consider the following:

```clj
[:process {:with ...
           :inputs [...]
           :output-fn (fn [result] ...)
           :scene ....}]

(defn- process!
  [{:keys [with inputs output-fn scene]} dispatch!]
  (.setCursor scene Cursor/WAIT)
  (future
    (try
      (-> (apply with inputs)
          output-fn
          (assoc :event/type :state*)
          dispatch!)
      (finally (.setCursor scene Cursor/DEFAULT)))))

(defmethod handle-event :state* 
  [event]
  (select-keys event [:state]))
```
I'm not sure if there is an even simpler way, but the above works beautifully and is pretty simple/generic. The only change it requires on `cljfx` is a tiny change to `fx/wrap-co-effects` to make sure you're not overwriting anything:

```clj
(defn wrap-co-effects
  [f co-effect-id->producer]
  (fn [event]
    (f
      (reduce-kv
        (fn [acc k v]
          (cond-> acc ;; careful not to overwrite anything!
                  (not (contains? acc k))
                  (assoc k (v))))
        event
        co-effect-id->producer))))
```
As you can see there is no functional difference - we're just being a bit more careful. With all this stuff in place, one can have an even-handler like the following:

```clj
(defmethod handle-event :process-payroll-files-in
  [{:keys [files-in ^ActionEvent fx/event]}]
  (if (every? some? files-in)
    {:process {:with   #(dc/compare-payroll %1 %2 false)
               :scene  (.getScene ^Node (.getTarget event))
               :inputs  files-in
               :output-fn (fn [result]
                            (let [[res offenders] result]
                              (if (= :ok res)
                                {:state {:ret {:text-out (if (seq offenders)
                                                           (with-out-str (ppr/print-table offenders))
                                                           "No discrepancies found ...")
                                               :values   offenders
                                               :count    (str (count offenders))}}}
                                {:state {:ret {:text-out offenders}}})))}}
    {:state {:ret {:text-out "File(s) missing ..."}}}))
```
I don't know if I'm overthinking this, as I couldn't find any cljfx-native examples  - only JavaFX ones (using `Task` class). In any case, it seems perfectly reasonable to me that `fx/wrap-co-effects` is a tiny bit more careful wrt to overwriting keys, which in turn enables a completely generic thread-processing effect that can be used for any long-running task.

**Comment by vlaaad** [comment]
Hi!

I'm not sure I'm following, why are any changes to `wrap-co-effects` necessary? If you want to be extra sure to avoid clashes, you can use namespaced keywords for effect identifiers, e.g. `:my-app.effect/process`.

**Comment by jimpil** [comment]
Ok, suppose I have the following renderer:

```clj
(def renderer
  (fx/create-renderer
    :middleware (fx/wrap-map-desc root-view)
    :opts {:fx.opt/map-event-handler
           (-> ctl/handle-event
               (fx/wrap-co-effects {:state (fx/make-deref-co-effect STATE)})
               (fx/wrap-effects {:state (make-swap-merge-effect STATE)
                                 :dispatch fx/dispatch-effect
                                 :process  process!}))}))
```
With this, my event handlers can return `:state`, but the `:process` effect can't, because the `:state` key will be overwritten by `fx/wrap-co-effect`. With the slightly altered version, this doesn't happen, and so I can actually propagate the new state from my processing effect. Does that makes sense?

**Comment by vlaaad** [comment]
Ah, I got you now! I think there is a problem that it is possible to have a clash between keys from co-effects and other keys in the event definition, and I think a better solution would still be ensuring that those are different keys with namespaced effect/co-effect keywords, but... 

The problem you are having is actually a different one — you want to dispatch an event that changes the state, but you put the new state as an argument to that event that clashes with co-effect. This could be fixed by making that key for state co-effect be different from the key for the state effect, e.g. `:state` and `:set-state`, but... 

I think the actual problem is that you have output-fn that pretends to be a real event handler but isn't. Just make it an event handler:
```clj
(defn- process! [{:keys [fn args on-success on-failure scene]} dispatch!]
  (.setCursor scene Cursor/WAIT)
  (let [[err result] (future
                       (try
                         [nil (apply fn args)]
                         (catch Exception e
                           [e nil])
                         (finally (.setCursor scene Cursor/DEFAULT))))]
    (if err 
      (dispatch! (assoc on-failure :fx/event err))
      (dispatch! (assoc on-success :fx/event result)))))
```

Then event handler becomes this:

```clj
(defmethod handle-event :process-payroll-files-in [{:keys [files-in ^ActionEvent fx/event]}]
  (if (every? some? files-in)
    {:process {:fn #(dc/compare-payroll %1 %2 false)
               :args files-in
               :scene (.getScene ^Node (.getTarget event))
               :on-success {:event/type :on-process-payroll-files-in-success}
               :on-failure {:event/type :on-process-payroll-files-in-failure}}}
    {:state {:ret {:text-out "File(s) missing ..."}}}))

(defmethod handle-event :on-process-payroll-files-in-success [{:keys [fx/event]}]
  (let [[res offenders] event]
    (if (= :ok res)
      {:state {:ret {:text-out (if (seq offenders)
                                 (with-out-str (ppr/print-table offenders))
                                 "No discrepancies found ...")
                     :values   offenders
                     :count    (str (count offenders))}}}
      {:state {:ret {:text-out offenders}}})))
```

What do you think?

**Comment by vlaaad** [comment]
There is an example that takes this approach for HTTP requests:
- effect definition: https://github.com/cljfx/cljfx/blob/master/examples/e18_pure_event_handling.clj#L28-L39
- usage: https://github.com/cljfx/cljfx/blob/master/examples/e18_pure_event_handling/events.clj#L31-L38

**Comment by jimpil** [comment]
Hmm I see your point...
Your example code won't quite work because `process` is now blocking, but I can easily fix that by calling `dispatch!` inside the future body.  I'll  pursue your approach and see if it feels more natural... Many thanks! 👍

**Comment by vlaaad** [comment]
Oh good point, and I also forgot to deref it. I should have put everything in the future call and do a let+try-catch in there. 
Bu the way, JavaFX is not threadsafe, you should call `.setCursor` only on the JavaFX thread (e.g. with `fx/on-fx-thread`).
