### ISSUE TITLE
Recommended way for binding properties?

### ISSUE THREAD

**Issue by jimpil** [cljfx/cljfx#108]
Hi there,

JavaFX provides a pretty flexible way to bind two properties together. For the sake of simplicity let's assume one is building a chessboard:
```clj
{:fx/type :stage
   :title   "Chess FX"
   :width   900
   :height  900
   :showing true
   :scene {:fx/type :scene
           :root {:fx/type :grid-pane
                  :children (for [x (range 8)
                                  y (range 8)]
                              {:fx/type :rectangle
                               :width 100  ;; bindable
                               :height 100 ;; bindable
                               :grid-pane/column x
                               :grid-pane/row y
                               :grid-pane/hgrow :always
                               :grid-pane/vgrow :always
                               :fill (if (zero? (rem (+ x y) 2))
                                        :white
                                        :black)})}}}
```
All good so far... Now let's assume that I want the whole thing to be resizable  - even the individual rectangles. In plain JavaFX this translates to this:

```java
 rect.widthProperty().bind(root.widthProperty().divide(8));
 rect.heightProperty().bind(root.heightProperty().divide(8));
```
I 'm not sure how to do this given the declarative nature of `cljfx`. I would expect that any component with bindable properties (e.g `widthProperty` & `.heightProperty` in `Rectangle`), would also support a bindings map roughly like so:

```clj
:bindings {:width (fn [^GridPane parent] 
                    (-> (.widthProperty parent)
                        (/ 8)))
          :height (fn [^GridPane parent]
                     (-> (.heightProperty parent)
                         (/ 8)))}
```

The idea is that instead of providing some raw property key and some static value, one can provide these keys inside a `:bindings` map, and have the engine `.bind` those to the result of the corresponding function (providing its parent as the argument). Any thoughts?

Many thanks in advance :)

**Comment by vlaaad** [comment]
Hi! Cljfx doesn't use bindings, because it has "bindings" in terms of props that might have the same values set in code, e.g.:
```clj
[{:fx/type :region :width x} {:fx/type :region :width x}] ;; 2 regions widths are "bound"
```
This is more powerful than JavaFX's bindings, but at the same time, in some cases such as the one you describe it's less powerful because JavaFX allows binding to dynamically changing properties such as resizable node width. A general workaround for these kinds of issues is using `fx/ext-on-instance-lifecycle` that can get a reference to the grid pane, query its children and bind them imperatively:
```clj
{:fx/type fx/ext-on-instance-lifecycle
 :on-created #(doseq [rect (.getChildrenUnmodifiable %)]
                (.bind (.widthProperty rect) (.divide (.widthProperty %) (int 8)))
                (.bind (.heightProperty rect) (.divide (.heightProperty %) (int 8))))
 :desc {:fx/type :grid-pane
        :children (for [x (range 8)
                        y (range 8)]
                    {:fx/type :rectangle
                     :grid-pane/row x
                     :grid-pane/column y
                     :fill (if (even? (+ x y)) :black :white)})}}
```

**Comment by jimpil** [comment]
Nice! `fx/ext-on-instance-lifecycle` looks very useful indeed... 👍
