### ISSUE TITLE
how to react pane size changing

### ISSUE THREAD

**Issue by LoveLiveSun** [cljfx/cljfx#109]
hello, i have a window it has a component like that:
`{:fx/type :pane
  ......
  :children [{:fx/type :image-view
                   ......}]}`
i want the size of image-view follow the size of pane, and i do not how to do it. i find some property listener in java like this `pane.widthProperty().addListener(listener)`.so i want to konw is cljfx has some like this or has some other way to finish this job.

**Comment by vlaaad** [comment]
Hi! Please see this discussion about wiring JavaFX bindings: #108
