### ISSUE TITLE
Not on FX application thread when creating a custom component

### ISSUE THREAD

**Issue by ertugrulcetin** [cljfx/cljfx#115]
Hi,

When I try to create a custom component of [CodeEditor.java](https://gist.github.com/jewelsea/1463485#file-codeeditor-java) I get this error;

```clojure
Execution error (IllegalStateException) at com.sun.javafx.tk.Toolkit/checkFxUserThread (Toolkit.java:292).
Not on FX application thread; currentThread = nREPL-session-a393a8f3-23b7-40cc-a479-ff9cc0f603b5

```

Here is my code that fails;
```clojure
(def ext-code-editor
  (fx/instance
   (fx/create-component
    {:fx/type fx/ext-instance-factory
     :create #(CodeEditor. "(some code)")})))
```

**Comment by vlaaad** [comment]
Hi! JavaFX is not thread-save, and some things can only be created/accessed/modified on JavaFX's UI thread. Cljfx's renderer abstraction, for example, performs all modifications to a display graph on the UI thread. You can wrap your form in `@(fx/on-fx-thread ...)` to invoke `...` on the UI thread and block until it's complete.

**Comment by ertugrulcetin** [comment]
Yes I also tried this one and got this error: **java.lang.IllegalArgumentException: No implementation of method: :create of protocol: #'cljfx.lifecycle/Lifecycle found for class: org.editor.CodeEditor**

```clojure
(def ext-code-editor
  @(fx/on-fx-thread
    (fx/instance
     (fx/create-component
      {:fx/type fx/ext-instance-factory
       :create #(CodeEditor. "10ms")}))))
```

**Comment by vlaaad** [comment]
Well, that's because `ext-code-editor` is an instance of an editor, not an. extension function to create code editor, that would be just `{:fx/type fx/ext-instance-factory :create #(CodeEditor. "10ms")}` :)

**Comment by ertugrulcetin** [comment]
@vlaaad thank you so much. It worked! I misunderstood the concept.
