### ISSUE TITLE
capture click events on table row

### ISSUE THREAD

**Issue by torkus** [cljfx/cljfx#118]
I need to capture a double-click event on a table-view's row.

[This is my table-view currently](https://github.com/ogri-la/strongbox/blob/ec65e5aae3bd9b20d618e73e442f32db9cc3150a/src/strongbox/ui/jfx.clj#L928-L951). I'm already using a `:row-factory` to apply row-level styling (thanks again for that), however adding a naive `:on-action` callback emits the error:

> java.lang.IllegalArgumentException: No implementation of method: :create of protocol: #'cljfx.lifecycle/Lifecycle found for class: nil

is this currently possible?

**Comment by vlaaad** [comment]
Hi @torkus!

This exception indicates that there is no `:on-action` property in `:table-row` component. You can evaluate `(sort (keys cljfx.fx.table-row/props))` to see available props in `:table-row` (or look at the code in `table_row.clj`).

I managed to capture double-click event using this code:
```clj
{:fx/type :table-view
 :row-factory {:fx/cell-type :table-row
               :describe (fn [x]
                           {:on-mouse-clicked
                            (fn [e]
                              (when (and (= javafx.scene.input.MouseButton/PRIMARY (.getButton e))
                                         (= 2 (.getClickCount e)))
                                (tap> :double-click)))})}
 :columns [{:fx/type :table-column :cell-value-factory identity}]
 :items (vec (range 20))}
```
This is basically a click listener that uses `.getClickCount` to check if it's a double click.

**Comment by torkus** [comment]
This is all very helpful, thanks again @vlaaad
