### ISSUE TITLE
text-wrap contents of table cells

### ISSUE THREAD

**Issue by torkus** [cljfx/cljfx#120]
I have a table with a column whose content may occasionally be very long. When this happens I get ellipses "..." but what I really need is for the text to wrap on to a new line. 

`:wrap-text true` on a `:table-cell-factory` like used in [this example](https://github.com/cljfx/cljfx/blob/babc2f09e4827efb29f859a442a1658d82169a62/examples/e16_cell_factories.clj#L21-L23) isn't working.

A [StackOverflow example in Java](https://stackoverflow.com/questions/22732013/javafx-tablecolumn-text-wrapping) suggests binding properties to re-calculate the preferred height but even that seems buggy.

Is this or can this be supported in cljfx?

**Comment by vlaaad** [comment]
Hmm, I tried to reproduce this example using cljfx:
```clj
{:fx/type :table-view
 :columns [{:fx/type :table-column
            :text "pr-str"
            :cell-value-factory identity
            :cell-factory (reify javafx.util.Callback
                            (call [_ col]
                              (let [text (javafx.scene.text.Text.)
                                    cell (doto (javafx.scene.control.TableCell.)
                                           (.setGraphic text)
                                           (.setPrefHeight javafx.scene.control.Control/USE_COMPUTED_SIZE))]
                                (.bind (.wrappingWidthProperty text) (.widthProperty col))
                                (.bind (.textProperty text) (.itemProperty cell))
                                cell)))}]
 :items (map #(apply str (repeat % "! ")) (range 10 100))}
```

Unfortunately, it did not work for me. Sorry, I don't know how I can help with that.

**Comment by torkus** [comment]
Nuts. Thanks for trying, I appreciate it.

**Comment by torkus** [comment]
actually, it appears to be working for me. Before:

![Screenshot at 2021-03-24 11-33-11](https://user-images.githubusercontent.com/48790775/112238539-c3070e00-8c94-11eb-9dc3-8502e8943f36.png)

after:

![Screenshot at 2021-03-24 11-32-40](https://user-images.githubusercontent.com/48790775/112238551-c7cbc200-8c94-11eb-8ec2-95008d95207c.png)

I'm having some issues with the table auto-resizing columns leading to a horizontal scrollbar, the fonts seem darker and that border looks a little off, but it seems to basically work.

**Comment by vlaaad** [comment]
Huh, interesting. I wonder why it didn't work for me. I think the color is different because JavaFX's default CSS color for Label is not black while Text's default color is black. Perhaps you could try using Label instead of Text? I think for the label you'll need to set `(.setTextWrap label true)`, and instead of `wrappingWidthProperty` use `prefWidthProperty` (or `minWidthProperty`, or a combination of both).
