### ISSUE TITLE
Resizable canvas example

### ISSUE THREAD

**Issue by cnuernber** [cljfx/cljfx#121]
Hey, I like the direction of this library and would like play around with it bit in a graphics app.

One thing I do need is a resizable canvas that simply calls the draw fn on resize.  Stack exchange links to this [javax tip](https://dlemmermann.wordpress.com/2014/04/10/javafx-tip-1-resizable-canvas/) on resizable canvas and this tip binds the canvas's width/height property to it's parent pane's width/height property which makes some sense.

How would you recommend doing this through the cljfx system?  

Related would be a simple example of using a custom javafx type in a scene.  It isn't clear to me how to link the custom type's keyword to its lifecycle from the documentation.

**Comment by vlaaad** [comment]
Hi! That's actually what I do in Reveal:
1. [resizable canvas](https://github.com/vlaaad/reveal/blob/master/src/vlaaad/reveal/canvas.clj)
2. [using (stack) pane parent](https://github.com/vlaaad/reveal/blob/master/src/vlaaad/reveal/output_panel.clj#L462-L478)

>  It isn't clear to me how to link the custom type's keyword to its lifecycle from the documentation.

You create a custom lifecycle and use it directly without keywords for indirection. In reveal it's defined [here](https://github.com/vlaaad/reveal/blob/master/src/vlaaad/reveal/canvas.clj#L37) and used [here](https://github.com/vlaaad/reveal/blob/master/src/vlaaad/reveal/output_panel.clj#L464).

Hope it helps :)

**Comment by cnuernber** [comment]
It absolutely does :-).
