### ISSUE TITLE
Suspicious code in `cljfx.composite/advance-composite-component`

### ISSUE THREAD

**Issue by frenchy64** [cljfx/cljfx#125]
From a code review I noticed the `:else` branch in `advance-composite-component` assumes that `new-e` is non-nil. In particular, this call could return `nil`:

https://github.com/cljfx/cljfx/blob/ec3c34e619b2408026b9f2e2ff8665bebf70bf56/src/cljfx/composite.clj#L80

Is this a bug?

**Comment by frenchy64** [comment]
After some thought, I think it's implied this is non-nil, because `k` either occurs in `props` or `props-desc`.

**Comment by vlaaad** [comment]
Yeah, it iterates on a union of old and new prop keys, so we can assume in `:else` branch that new entry exists.
