### ISSUE TITLE
Editable cells in tableview (example 32)

### ISSUE THREAD

**Issue by dsbw** [cljfx/cljfx#130]
Going through example 32: This demonstrates editable cells in a tableview. It's very cool that you can swap out the plain text edit for (what seems like) practically arbitrary other components. 👍(The real challenge for me is going to be having a tableview drop-down for a cell grid, but I hope that's as easy as the other drop-ins I've tried.)

I'm trying to build a data-entry-heavy app—indeed, it's part of the reason I want to use JavaFX over a web app—and am trying to work out the following oddities that appear in the example:

1. To put the cell into edit mode requires a double-click, but this must be followed by a third click in order for the cell to actually grab the (keyboard) focus.
2. Pressing [tab] ends up going to the age filter checkbox. Ideally, it should go to the next editable cell on the row, or a new row if at the last cell on the row.

I'm not seeing how I would go about either of these changes.

If it would be helpful to other users, I could maybe work out a table-view demo that showed off more of the possibilities and was very touch-typist friendly.

**Comment by vlaaad** [comment]
Hi,

Those are tough questions in JavaFX. Even when using built-in "editable" features, IIRC there are some bugs with edited values being not committed in some cases when changing focus. What I'm trying to say is unfortunately either way it's going to look ugly.

For triple-click, there is a solution — auto-focusing the node when it's shown on stage. This is done with the following code:
```clj
;; code that does auto-focus on show:

(defn focus-when-on-scene! [^Node node]
  (if (some? (.getScene node))
    (.requestFocus node)
    (.addListener (.sceneProperty node)
                  (reify ChangeListener
                    (changed [this _ _ new-scene]
                      (when (some? new-scene)
                        (.removeListener (.sceneProperty node) this)
                        (.requestFocus node)))))))

;; using it in the e32 will change `editable-cell` like so:

(defn- editable-cell [{:keys [fx/context id attr value-converter]}]
  (let [edit (fx/sub-val context :edit)
        value (fx/sub-ctx context value-sub id attr)]
    (if (= edit [id attr])
      {:fx/type fx/ext-on-instance-lifecycle
       :on-created focus-when-on-scene!  ;; using it with `ext-on-instance-lifecycle`
       :desc {:fx/type :text-field
              :on-key-pressed {:event/type ::key-pressed}
              :text-formatter {:fx/type :text-formatter
                               :value-converter value-converter
                               :value value
                               :on-value-changed {:event/type ::edit
                                                  :attr attr
                                                  :id id}}}}
      {:fx/type :label
       :on-mouse-clicked {:event/type ::on-cell-click :id id :attr attr}
       :text (str value)})))
```

Regarding `[tab]` behavior, I don't have a solution off the top of my head, but I would suggest experimenting with `:event-filter` on these cells that catches Tab KeyEvents and stops event propagation to disable default behavior, and then doing the switch in code.

**Comment by dsbw** [comment]
Thanks, vlaaad! I appreciate it. I will try these out.

A good, full-featured tableview is pretty critical to a desktop app. It's been my #1 struggle in deciding what library to use. When you say "it's going to look ugly" do you mean the code or the final app? I can manage the former, but the latter—I can't have my users looking at ugly tables.

**Comment by vlaaad** [comment]
I meant the code. Javafx uses CSS for styling, you can make it look pretty good. Also, if you want to make custom look-and-feel, I suggest looking at https://github.com/cljfx/css. Iterating on CSS with live reload is a bliss!

**Comment by dsbw** [comment]
Oh, phew! 😅 I need the look-and-feel to be smooth.

I haven't gotten so far as to use the cljfx/css library. I have noticed that if I change my CSS, when I bring the form back up, it reflects the new CSS...does cljfx/css do it, like, *LIVE* so that if you change the background color in the CSS, it changes it before your very eyes?

**Comment by vlaaad** [comment]
With a bit of a setup, yes, you can configure it in a way that updates the UI when you redefine the CSS at the REPL :)

**Comment by dsbw** [comment]
This worked really well! I did a crude "capture the TAB" to move from name->age which I can generalize:

```
(defmethod event-handler ::key-pressed [{:keys [fx/context ^KeyEvent fx/event]}]
  (let [{:keys [edit]} (:cljfx.context/m context)]
    (when (= (.getCode event) KeyCode/ESCAPE)
      {:context (fx/swap-context context dissoc :edit)})
    (when (= (.getCode event) KeyCode/TAB)
      (if (= :user/name (last edit))
        {:context (fx/swap-context context assoc :edit [(first edit) :user/age])}
        {:context (fx/swap-context context dissoc :edit)}))))
```

And I found I had to modify the edit event handler from:

```
(defmethod event-handler ::edit [{:keys [fx/context fx/event attr id]}]
  {:context  (fx/swap-context context dissoc :edit)
   :transact [[:db/add id attr event]]})
```

To:

```
(defmethod event-handler ::edit [{:keys [fx/context fx/event attr id]}]
  {:transact [:update id attr event]})
```

Because if I dissociated the :edit when the data was entered, it wouldn't know where to go when it saw the tab.

**Comment by vlaaad** [comment]
Awesome! It's unfortunate that this problem is the incidental complexity of JavaFX and cljfx, but I'm glad you found a solution!
