### ISSUE TITLE
E15 Modification Question

### ISSUE THREAD

**Issue by dsbw** [cljfx/cljfx#132]
I've got two things I'm still struggling with: Lifecyle and the contexts. So I took E15, which has this:

```
(def renderer
  (fx/create-renderer
    :middleware (comp
                  fx/wrap-context-desc
                  (fx/wrap-map-desc (fn [_] {:fx/type root})))
    :opts {:fx.opt/map-event-handler event-handler
           :fx.opt/type->lifecycle   #(or (fx/keyword->lifecycle %)
                                          (fx/fn->lifecycle-with-context %))}))

(fx/mount-renderer *state renderer)
```
And I changed it to use your skeleton code:
```
(def app
  (fx/create-app *state
                 :event-handler event-handler
                 :desc-fn (fn [_]
                            {:fx/type root})))
```
It shows up, and it seems to work BUT I get an error on taking any action:
```
clojure.lang.ExceptionInfo: Effect :cljfx.context/m does not exist {:effect :cljfx.context/m, :existing-effects (:context :dispatch)}
	at cljfx.event_handler$wrap_effects$dispatch_sync_BANG___2154.invoke(event_handler.clj:31)
```

**Comment by vlaaad** [comment]
Did you change the actions as well? You probably need to, because `create-app` works on effects/co-effects — see [e22](https://github.com/cljfx/cljfx/blob/master/examples/e22_button_with_confirmation_dialog.clj) for create-app example.

**Comment by dsbw** [comment]
I didn't change the actions; I'm not sure how I would. Looking at e22, I don't see how it's _different_ from e15. e22 doesn't seem to use the fx/wrap-co-effects or fx/wrap-effects, they both seem to use roughly the same keys parameters (fx/event, fx/context).

What am I missing?

**Comment by vlaaad** [comment]
`create-app` adds effects/co-effects for you, so you need to use them as in e22, i.e. you need to return a map with keys like `:context` or `:dispatch`. Calling `swap!` will return the new value of a context, which is not the expected return, hence the error you are seeing

**Comment by dsbw** [comment]
A HA!!! THAT'S IT! Thank you!!

```
(defmethod event-handler ::assign-user [{:keys [task-id fx/event]}]
  {:context (swap! *state fx/swap-context assoc-in [:tasks task-id :assignee] (:id event))})

(defmethod event-handler ::set-state [{:keys [task-id fx/event]}]
  {:context (swap! *state fx/swap-context assoc-in [:tasks task-id :state] event)})
```
OK, it's starting to make a little more sense.

**Comment by vlaaad** [comment]
Glad I could help :D

**Comment by vlaaad** [comment]
Wait, you did it wrong :P 

effects do the swap themself, so your event handler can be a pure function, so it should be something like 

```clj
(defmethod event-handler ::assign-user [{:keys [task-id fx/event fx/context]}]
  {:context (fx/swap-context context assoc-in [:tasks task-id :assignee] (:id event))})
```

**Comment by dsbw** [comment]
Yes, that's right. I did that in my own project, even if I screwed up the example. =P
