### ISSUE TITLE
How can I invoke methods like sizeToScene?

### ISSUE THREAD

**Issue by expez** [cljfx/cljfx#133]
If I have something like this:

```clj
(defn- window [{:keys [fx/context]}]
  {:fx/type :stage
   :scene
   {:fx/type :scene
    :root {:fx/type :scroll-pane
           :content
           {:fx/type :v-box
            :spacing 10
            :padding 5
            :children
            [{:fx/type :label
              :style {:-fx-font-size 16
                      :-fx-font-weight :bold}
              :text "My label"}
             {:fx/type :text-field
              :on-text-changed {:event/type ::my-event}}
             {:fx/type list-view}]}}}})

(def app (fx/create-app context :event-handler map-event-handler
                        :desc-fn (fn [_] {:fx/type window})))
```

And I want to call [sizeToScene](https://docs.oracle.com/javase/8/javafx/api/javafx/stage/Window.html#sizeToScene--)  on the window, how can I do that?  The javafx classes don't have many methods that aren't managing properties, so this is the first method call I've missed.

PS: Thanks for your hard work!  This library--and all the examples--is a joy to work with 💯

**Comment by vlaaad** [comment]
Hi! The easiest way to do that is using `fx/ext-on-instance-lifecycle` that will receive JavaFX node in its callbacks, and using `:on-created` to do some extra setup.

**Comment by expez** [comment]
That worked beautifully!  Thanks for your help! 👍
