### ISSUE TITLE
Accessing View Details

### ISSUE THREAD

**Issue by dsbw** [cljfx/cljfx#136]
Hi, Vlaa(a?)d! 

So I'm building out these editable tables, and I use a function, (not yet streamlined):

```
(defn editable-table [columns items]
  {:fx/type :table-view
   :columns columns
   :items   items})
```
I create tables by passing in the columns and how to fetch table contents, like so:

```
 :content  (editable-table [["Code" :code]
     ["Data" :data]]
    (get-in context [:cljfx.context/m :selected-item]))
```
(Side note, I always think I'm doing something wrong if I have to address the "cljfx.context/m" key. It feels like I should only get the actual relevant context.)

For purposes of tabbing through the editable columns, I need to know that "code" is followed by "data" and "data" is that last column. Now, I could make a master map of :table-name/column-name so that in my main handler:
```
(if next-column
        {:context (fx/swap-context context assoc :edit [(first edit) (lookup-current-column-and-figure-out-what-next-column-is)])}
        {:context (fx/swap-context context dissoc :edit)})
```
Then I just pass in the current column from the editable-cell routine:
```
:on-key-pressed {:event/type :edit-next-column :next-column attr} ;"attr" contains the current column name.
```
But if we go back to the editable-table routine, clearly the table-view knows which column is next and it seems like something the column should know (who are my neighbors to the right and left?). I could shoehorn that in on the columns line:
```
(defn editable-table [columns items]
  {:fx/type :table-view
   :columns (routine-that-processes-columns-and-links-them-together columns)
   :items   items})
```
But this seems like a dubious idea. Actually, doing anything other than asking the table "Hey, what is the order of your columns?" seems dubious, since you could get into a situation where you're dynamically rearranging columns.

How do I look at the current, focused, being-edited table and get the column info? Am I making this over-complicated?

**Comment by dsbw** [comment]
Worked this one out. I thought, "Well, I'll go into the `table-view` in the `on-created` and get the column order from there," which would've been an interesting look into the lifecycle/properties stuff—but also way too complicated. I realized that since I was passing in the column to the table field, I could just use that (duh!):
```
(defn editable-table
  ([columns items]
   (editable-table columns items ::select-single))
  ([columns items event-type]
   (let [column-order (map second columns)]
     {:fx/type fx.ext.table-view/with-selection-props
      :props   (cond-> {:selection-mode           :single
                        :on-selected-item-changed {:event/type event-type}})
      :desc    {:fx/type :table-view
                :columns (map #(apply (partial etc column-order) %) columns)
                :items   items}})))
```
The `editable-table` routine is a bit more involved now because I'm using `with-selection-props`, but the real work is creating the `column-order`
```
   (let [column-order (map second columns)]
```
Basically, the user defines columns as:
```
 ["Header" :data-key {:option-map :option-value}]
```
So, `map second` is just pulling all the data-keys. Meanwhile, `etc` (for **e**ditable **t**able **c**ell) uses the code from example e32:
```
(defn etc
  ([column-order header data-column]
   (etc column-order header data-column nil))
  ([column-order header data-column option]
   {:fx/type            :table-column
    :visible            (not (:hidden option))
    :text               header
    :cell-value-factory identity
    :cell-factory       {:fx/cell-type :table-cell
                         :describe     (make-attr-cell-factory editable-cell data-column :default (:functions option) column-order)}}))
```
And I've modified `editable-cell` from that example to observe the column order:
```
(defn editable-cell [{:keys [fx/context id attr value-converter functions column-order] :as e}]
  (let [edit (fx/sub-val context :edit)
        value (attr id)
        next-column (if column-order (nth column-order (inc (.indexOf column-order attr)) nil))]
```
Then I just fire off an `edit-next-column` event which I can handle generically!

**Comment by vlaaad** [comment]
Awesome, glad you worked it out!
