### ISSUE TITLE
View the component tree?

### ISSUE THREAD

**Issue by dsbw** [cljfx/cljfx#145]
There are multiple references in the readme about "the component tree", which I take to be the node graph or a proxy thereof.

Is there a way to see/dump the whole thing?

**Comment by vlaaad** [comment]
There is no accessible way to do that, unfortunately. You get component tree data structure when using `fx/create-component`, and it's gigantic and could use a lot of filtering. When you are using a renderer, this state is hidden inside.

**Comment by dsbw** [comment]
Bummer. Thanks!
