### ISSUE TITLE
Possible to get access to underlying objects?

### ISSUE THREAD

**Issue by dsbw** [cljfx/cljfx#147]
I know we can't get the scene graph from previous issues, but can we get a handle to any specific object? In Java, I have this code:
```
public void adjustButtons() {
        var tallest = 0.0;
        for (Node n : buttonBar.getButtons()) {
            var ht = ((Button) n).getHeight();
            if (tallest < ht) tallest = ht;
        }
        for (Node n : buttonBar.getButtons()) {
            ((Button) n).setMinHeight(tallest);
        }
    }
```
What it does is look for the tallest `Button` in the `ButtonBar`, and then makes all the buttons in the button bar that height. This is necessary because while `ButtonBar` lets you require all buttons be the same width, it pretty much does whatever it wants with heights with no way to make them uniform.

**Comment by vlaaad** [comment]
Hi! You can access underlying objects at different points in those objects' lifecycles using `fx/ext-on-instance-lifecycle`, e.g.:
```clj
{:fx/type fx/ext-on-instance-lifecycle
 :on-created adjust-buttons!
 :desc {:fx/type :button-bar ...}}
```

**Comment by dsbw** [comment]
```
{:fx/type fx/ext-on-instance-lifecycle
 :on-created adjust-buttons!
 :desc {:fx/type :button-bar ...}}
```
I did this and the `adjust-buttons` method was called, but at the time of being called the dimensions of the buttons are all 0, which doesn't surprise me. In my Java analogue, the call is always made after the `onShow`. So I think I need to...add another element to the lifecycle?

I've been looking at the lifecycle without grasping how it works, but I guess that's another question.

**Comment by vlaaad** [comment]
You can do fx/run-later in adjust buttons to skip a tick :)

**Comment by dsbw** [comment]
THAT helps A LOT!

Thank you!
