### ISSUE TITLE
Using sub-* for NOT rendering the UI

### ISSUE THREAD

**Issue by dsbw** [cljfx/cljfx#149]
Hi, again, Vlaad,

Thanks for walking me through #146 . I think I understand a lot better now. In that thread, you said this:

> Also :cljfx.context/... keywords are implementation details, you should never use them, instead it should be fx/sub-* to access context content

In most cases, I can clearly see my confusion in trying to grab the context and look into it directly, but in some instances my thinking was basically "Well, I don't want to _subscribe_ to _anything_! I want to know the state right now so that I can _do_ something." Consider:

```
(defmethod event-handler :buy-book [{:keys [fx/context]}]
  (let [ddn (get-in @*context [:cljfx.context/m :selected-entry :dewey-decimal-number])
        author (get-in @*context [:cljfx.context/m :selected-author :name])
        title (get-in @*context [:cljfx.context/m :selected-title])]
    (buy-book ddn author title))
```
I can replace this with:
```
(defmethod event-handler :buy-book [{:keys [fx/context]}]
  (let [ddn (fx/sub-val context get-in [:selected-entry :dewey-decimal-number])
        author (fx/sub-val context get-in [:selected-author :name])
        title (fx/sub-val context :selected-title)]]
    (buy-book ddn author title))
```
And it will work, but I'm not really clear what I have done. Buying a book is a discrete instance that needs only momentary access to the data. Am I creating new relationships every time I go into the :buy-book handler? And are they piling up?

**Comment by vlaaad** [comment]
What sub-* fns do is that they calculate the output of your subscription function and cache it so it's not run again on the same instance of context. It's only a problem of you don't use core.cache with your context

**Comment by vlaaad** [comment]
There are no relationships created, only entries in the cache

**Comment by dsbw** [comment]
OK, thanks. I need to study a little more how the reactive part works because I had the idea that sub-* was specifically meant for "update this view when this value changes".

**Comment by vlaaad** [comment]
> update this view when this value changes

Well, that's right, these are the semantics. It's just that they are achieved using caching of calculation results instead of observables and subscriptions

**Comment by dsbw** [comment]
So, you could just as well have a "get-val" function, but it would do the same thing, essentially. It's just a naming thing. Cool.
