### ISSUE TITLE
depstar is deprecated and archived; switch to tools.build

### ISSUE THREAD

**Issue by seancorfield** [cljfx/cljfx#157]
`depstar` has been deprecated and archived for six month now; I'm encouraging everyone to switch to `tools.build`. My `build-clj` wrapper makes it easier to switch.

**Comment by seancorfield** [comment]
Note: at this point, the `build-clj` wrapper is also archived so using plain `clojure.tools.build.api` with `build.clj` is the way to go.

**Comment by vlaaad** [comment]
Thanks for the pointer. So far, I'm happy with the discontinued depstar btw.
