### ISSUE TITLE
Broken encoding for Sanskrit text in WebView

### ISSUE THREAD

**Issue by licht1stein** [cljfx/cljfx#164]
I'm building a Sanskrit dictionary and use devanagari font for it. I tried using WebView to display dictionary articles, but the devanagari letters get corrupter. `<meta charset="UTF-8">` in HTML is ignored or doesn't help. How can I fix this?

**Comment by vlaaad** [comment]
Hey @licht1stein! This issue is related to JavaFX and not cljfx; unfortunately, I can't help with it as I didn't encounter this issue before and don't know enough about WebView's font rendering and encodings.

**Comment by licht1stein** [comment]
Thank you!
