### ISSUE TITLE
Using cljfx with Gradle

### ISSUE THREAD

**Issue by Vlsarro** [cljfx/cljfx#169]
Hello. I have some issues using cljfx with Gradle. [Example project](https://github.com/Vlsarro/sample-clojurephant-cljfx-app). The error is present if line ([build.gradle#L38](https://github.com/Vlsarro/sample-clojurephant-cljfx-app/blob/master/build.gradle#L38)) is commented out.

When I specify cljfx as a dependency and run `runShadow` command I have this output:
```
$ ./gradlew runShadow

> Task :checkClojure FAILED
Execution error (FileNotFoundException) at cljfx.platform/eval1625$loading (platform.clj:1).
Could not locate cljfx/jdk/platform__init.class, cljfx/jdk/platform.clj or cljfx/jdk/platform.cljc on classpath.
```

As I understand Gradle cannot resolve cljfx dependencies specified in profiles of [pom.xml](https://github.com/cljfx/cljfx/blob/master/pom.xml) (related issue -> https://github.com/gradle/gradle/issues/19225). So it does not recognize profiles and doesn't add their dependencies to project dependency tree. And it means that platform code is not loaded, hence the error.

Currently I have manually added the required jar file (jdk11 ver, line [build.gradle#L38](https://github.com/Vlsarro/sample-clojurephant-cljfx-app/blob/master/build.gradle#L38)) and it works. But it is a hack. May be I am missing something, could someone please take a look?

**Comment by vlaaad** [comment]
Hi! It seems Gradle has very limited support for the profile activations feature of poms. Your hack is the right solution to the problem.

**Comment by Vlsarro** [comment]
Thank you for a quick response! I thought there was a more elegant way to solve this. Maybe some way to set profile in the build.gradle file or something but no matter how much I tried, it didn't work. Anyway, thank you for this nice library :)

**Comment by ajoberstar** [comment]
A verbose workaround to this is to use [Gradle's component metadata rules](https://docs.gradle.org/current/userguide/component_metadata_rules.html#making_variants_published_as_classified_jars_explicit) to tell Gradle that cljfx has a JDK11 variant.

```kotlin
dependencies {
  components {
    withModule<CljfxRule>("cljfx:cljfx")
  }

  implementation("cljfx:cljfx:1.9.3")
}

@CacheableRule
abstract class CljfxRule : ComponentMetadataRule {
  override fun execute(context: ComponentMetadataContext) {
    listOf("compile", "runtime").forEach { base -> addVariant(context, base) }
  }

  private fun addVariant(context: ComponentMetadataContext, base: String) {
    context.details.addVariant("${base}Jdk11", base) {
      attributes {
        attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 11)
      }
      withFiles {
        removeAllFiles()
        addFile("${context.details.id.name}-${context.details.id.version}-jdk11.jar")
      }
    }
    context.details.withVariant(base) {
      attributes {
        attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 8)
      }
    }
  }
}
```

This example uses Kotlin script, but you can see their official doc linked above for a Groovy example.

**Comment by vlaaad** [comment]
This looks very useful! Just FYI, latest cljfx release now has 3 activation profiles based on JDK versions:
1. [1.8-11)
2. [11-17)
3. [17,)
