### ISSUE TITLE
how to pass args to constructors

### ISSUE THREAD

**Issue by hendecahedron** [cljfx/cljfx#171]
how does one pass arguments to javafx constructors ?
e.g. the https://docs.oracle.com/javase/8/javafx/api/javafx/scene/PerspectiveCamera.html#PerspectiveCamera-boolean- constructor takes `boolean fixedEyeAtCameraZero` but I can't see how to do this in cljfx. I can do `{:fx/type :perspective-camera}` but what special key can I include for constructor args ?

**Comment by vlaaad** [comment]
Typically, if cljfx-controlled JavaFX object can be created using a zero-arg constructor, it will always be used, assuming every property can be configured with setters, which is usually the case with JavaFX. Is it possible to reproduce the effect of what you want to achieve using these properties? If it's not possible, I should add a way to do that. Meanwhile, you will be able to instantiate the camera yourself using `fx/ext-instance-factory` extension lifecycle.

**Comment by hendecahedron** [comment]
thanks, in this case `fixedEyeAtCameraZero` of `javafx.scene.PerspectiveCamera` is private and only settable via a constructor (or via reflection after construction with the zero-arg constructor I guess)

**Comment by vlaaad** [comment]
Try [`1.7.23`](https://github.com/cljfx/cljfx/blob/master/CHANGELOG.md#1723---2023-05-15) with the new `:fixed-eye-at-camera-zero` prop :)
