### ISSUE TITLE
Memory reuse with `fx/ext-instance-factory`

### ISSUE THREAD

**Issue by kxygk** [cljfx/cljfx#174]
This might not be a bug/issue - but I just found the behavior rather surprising b/c I've never had memory reuse issues in Clojure before

I created a minimal repro repo

https://github.com/kxygk/demo-cljfx-svg/

First I will note that this triggers a crash/error in this minimal example - but in my larger application it didn't trigger anything so it took a bit to track down. (more generally I will get crashes/error on launch, but sometimes nothing on rerender) - Hopefully this is useful for someone

Background: I'm using the FranzXaver library to read an SVG string and turn it into a JFX Node. I then display it in my application :)

To display an externally generated Java Node with `cljfx` I understand that I need to use `fx/ext-instance-factory`. I added a little helper/wrapper to do that:

```clojure
(defn
  svg
  "The actual workmap svg (as a JFX component"
  [{:keys [fx/context
           svg-group]}]
  {:fx/type fx/ext-instance-factory
   :create  (fn []
              svg-group)})
```

It takes a Node on the `:group` key and I can put this `svg` as a `fx/type` into my GUI tree

In the `ns` I create a SVG Node as a `def` 

```
(def
  circle-group
    (svg2jfx/batik-load circle-svg))
```

But! if I try to display it multiple times, I get an error

```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
java.lang.IllegalArgumentException: Children: duplicate children added: parent = Grid hgap=0.0, vgap=0.0, alignment=TOP_LEFT
	at javafx.scene.Parent$3.onProposedChange(Parent.java:561)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113)
...
```

The relevant line is commented out here:
https://github.com/kxygk/demo-cljfx-svg/blob/master/gui.clj#L71

```
{:fx/type  :grid-pane
 ;; ......
 :children [{:fx/type          svg
             :svg-group        (svg2jfx/batik-load circle-svg)
             :grid-pane/row    1
             :grid-pane/column 0}
            {:fx/type          svg
             :svg-group        (svg2jfx/batik-load circle-svg)
             :grid-pane/row    1
             :grid-pane/column 1}
            {:fx/type          svg
             :svg-group        circle-group
             :grid-pane/row    2
             :grid-pane/column 0}
            {:fx/type          svg
             :svg-group        circle-group   ;; <- ERROR: It's unhappy about this duplicate
             :grid-pane/row    2
             :grid-pane/column 1}]}
```
Here I  make a grid of 4 circles. The first two reload the SVG - creating new Nodes. In the second two circles I try to reuse the one loaded Node (from the previous `def`) b/c this rendering operation is slow - and it gets unhappy/crashes

It's been a million years since I've written any Java, but this was kinda unexpected b/c everything is typically pass-by-value. Would be curious to know if "I'm holding it wrong" and just maybe doing something wrong here on a more conceptual level (like it could be related to the lambda that's created in the `svg` function)

**Comment by vlaaad** [comment]
Hey! 

JavaFX disallows reusing the same Node instance in a scene graph multiple times. Because of this, you cannot use `fx/ext-instance-factory` to return the same node multiple times, instead, you should create a fresh node every time, e.g.:
```clj
(defn
  svg
  "The actual workmap svg (as a JFX component"
  [{:keys [fx/context
           svg-string]}]
  {:fx/type fx/ext-instance-factory
   :create  (fn []
              (batik-load svg-string))})
```

**Comment by kxygk** [comment]
I think I see what you're saying

`batik-load` is a slow call and I originally didn't want to reparse the SVG string and regenerate the Node each time. As I understood, with your design the `svg` Node will get regenerated with `batik-load` only when the `:svg-string` key has changed..  right? It seems to accomplish the same result as long as you don't try to redraw the same SVG Node many times which fits my usecase  :)) though I think it'd be suboptimal if you were say reusing a SVG Icon all over an application (and therefore calling `batik-load` a bunch)

My original plan was to load the Node once and to then store it in a subscription context. And then I'd reuse the Node directly when I want to draw it some place - but I was unclear on how to force the Node's duplication. I think it'd also allow me to resize the Node dynamically as the window size changed (while here I'd have to reparse the svg and make a new Node) I guess my big picture question was, shouldn't the Node have gotten automatically copied/duplicated when you do the `svg` function call since things are pass-by-value?

I'm a bit hazy on the details.. doing things my way while also ensuring you are not redrawing the Node when the state/subscription hasn't changed seems a bit more challenging. I do like that with your solution you don't need to save opaque objects in the context

**Comment by vlaaad** [comment]
Yeah as I understand it won't be re-created unless the SVG string changes. I don't see any way around it because this is how FranzXaver's SvgLoader class works — it only creates nodes from the input stream or file, and the nodes cannot be reused in multiple places. It would be nice if parsing and creating Nodes could be separated into independent steps, but judging by [the source code](https://github.com/afester/FranzXaver/blob/develop/FranzXaver/src/main/java/afester/javafx/svg/SvgLoader.java) it's not possible.

**Comment by kxygk** [comment]
Alright, I'm going to use your implementation for now b/c it serviceable and keeping the code simpler. :) Thank you for your help. I'll shave this yak later and put up a more complete solution here

Your fix does make my larger app non longer resizeable (b/c the redraw is way too slow). I should extend the demo app later to show what I mean. But FranzXaver SVG Nodes can be resized, so if you keep them in the subscription context you can reuse the Node and just rescale it. I'll just need to poke around and see how to clone the Nodes in the right place

**Comment by vlaaad** [comment]
Good luck :)
