### ISSUE TITLE
Reacting to changes in width/height

### ISSUE THREAD

**Issue by geokon-gh** [cljfx/cljfx#34]
I'm trying to have my code react to a change in the window's height/width (it's generating a custom plot though thing/geom and a SVG to JFX thing I have set up) and I'm a bit confused as to how to set this up properly

From what I'm seeing a `:stage` will include the properties of `:window`
https://github.com/cljfx/cljfx/blob/master/src/cljfx/fx/stage.clj#L14
And a `:window` will have a `:on-width-changed` property to which I can hook up an event handler
https://github.com/cljfx/cljfx/blob/master/src/cljfx/fx/window.clj#L29
However unlike most lines that of the form
` :on-blahblah [:setter lifecycle/event-handler :coerce coerce/event-handler]`
this one has a 
`:on-width-changed [:property-change-listener lifecycle/change-listener]`

Hooking up another entry in my event handler multimethod doesn't seem to be working properly

It's defined here: https://github.com/cljfx/cljfx/blob/master/src/cljfx/lifecycle.clj#L156

But I don't really understand the code.

My guess is that somewhere in my renderer setup 
```clojure
(def renderer
  (fx/create-renderer
   :middleware (fx/wrap-map-desc assoc :fx/type root)
   :opts {:fx.opt/map-event-handler event-handler}))
```
I need to add a second type of event handler? However I can't hunt down the right incantation in the code

My million dollar stupid question is - what's a **lifecycle**? It's used freely in the *README* and all over the code, but the only explanation I'm finding is at the end of the *README* that starts with "Lifecycle is well, a lifecycle of a component. [...] "

Is this a term from React? Or some Clojure design pattern? I can't tease out what it means and yet it's the backbone of the whole system :)

**Comment by vlaaad** [comment]
Lifecycle is a behavior that manages how things get created from description, changed to other value from previously created when description changes, and destroyed when description no longer exists. There are many of them for different kins of situations. 
As a user, you can consider `lifecycle/event-handler` and `lifecycle/change-listener` an implementation details that are irrelevant and just remeber this rule: all props for observing changes accept either a function or a map:
```clj
;; with this description it'll print whenever width is changed, useful for 
;; trying props for observing changes

{:fx/type :stage
 :on-width-changed #(prn :on-width-changed %)}

;; with this description your map event handler will receive map like 
;; {:foo "bar" :fx/event new-value}

{:fx/type :stage
 :on-width-changed {:foo "bar"}}
```

> Hooking up another entry in my event handler multimethod doesn't seem to be working properly

Can you tell me how it is not working properly? Your renderer setup looks perfectly fine, I think, the only thing I would have changed there is replace `(fx/wrap-map-desc assoc :fx/type root)` with `(fx/wrap-map-desc #(assoc % :fx/type root))` so it will access `root` through var lookup: it allows redefining `root` during development be reflected in app updates.

**Comment by geokon-gh** [comment]
I guess I was on the right track :) The issue turned out to be just an old version of cljfx that didn't have that property. Now everything is hooked up and working sorta

In your workflow how do you typically go about inspecting the available props from the REPL? Do you just open up the cljfx source a poke around?

**Comment by vlaaad** [comment]
Yep, that's what I do. Not 100% happy about it, but it works good enough.

**Comment by geokon-gh** [comment]
Thanks again for your help and guidance :)

**Comment by geokon-gh** [comment]
Hey @vlaaad , I think I found a lingering issue with using `:on-height-changed ` stage/window events 

It seem to ends up including the height of the window titlebar. And there is no clear way to subtract the title bar size. I can bake in some value for my machine, but the title bar will change between machines?

Do you have some workaround for tracking the actual size of the scene?

it's a bit silly, but I have a sub element that is rendered in a separate library, so i need to calculate the size it has available and then render it to the correct size so it fits

**Comment by vlaaad** [comment]
I [released](https://github.com/cljfx/cljfx/blob/master/CHANGELOG.md#167---2020-03-21) new version 1.6.7 which adds `:on-width-changed` and `:on-height-changed` props for scene as well: it does not include window title bar. 

Some day I'll go through all read-only properties and add change listener props for them...

**Comment by geokon-gh** [comment]
Thank you for pushing that addition :)) . I'm sorry I'm not able to make a PR myself. I'm still trying to grok the internals
