### ISSUE TITLE
JavaFX8 Support

### ISSUE THREAD

**Issue by joinr** [cljfx/cljfx#45]
I have reason to maintain presence on javafx8, namely oracle's Java8SE, due to legacy circumstances.  I went ahead and patched cljfx to support Javafx8 [here](https://github.com/joinr/cljfx/tree/eight).  I tried to be as non-invasive as possible, and ended up with one major change in platform init (checking to see if version 8 is present), and modifying the properties maps for several controls.  There seem to be new properties in 11 (thankfully old properties weren't deprecated).  So I defined a macro in cljfx.composite, modern-props, which wraps the props macro.  If the version (defined in new ns cljfx.version) is :eight, the modern-props emits nil.  This works well in bifurcating the existing map-based property definitions for controls.  I went through all the included examples in /examples, and followed the same process (discovering reflection errors to due expanded properties, then cordoning them off with the macro).  In some cases there were extant reflection warnings for proxies (typically proxy-super methods).  I patched these with hints/casting.

In all, the examples all render and work on my end running ZuluFX (Zulu openjdk + OpenJFX8).  I believe they will work with other compatible jdk's (Oracle, and BellSoft).

Due to the JavaFX versioning being tied to JDK, it's a bit of mess with dependencies.  fn-fx manages this with different profiles basedon jfx11 or not.

Note: the only exercising of this patch is what was around in the examples and what clojure tossed up in reflection warnings.  It's possible that users could be following a javafx11 tutorial and trying to use properties on a javafx8 system and run into problems.  I think that the examples cover a good deal of functionality though.  I'd think this is more of a legacy platform for users who need to maintain code on Java8 systems (since Oracle screwed the pooch and didn't provide a bridging strategy :/).

**Comment by vlaaad** [comment]
Hi, I was considering this for a while, thanks for giving a reference, it will be easier to add java 8 support with your help :+1:

**Comment by vlaaad** [comment]
Created jdk8 branch. Refactored diverging paths to be at different source trees, added `:jdk8` alias to use correct source paths + remove unnecessary deps. Found [a bug in tools-deps](https://clojure.atlassian.net/browse/TDEPS-142), so probably should wait with merging into master.

**Comment by vlaaad** [comment]
Remaining: figure out future maven releases.
Possible options:
- different artifact
- classifiers
- maven profiles with [activation](http://maven.apache.org/pom.html#Activation) by JDK version.

**Comment by joinr** [comment]
That's great.  I didn't know about activations.  I think that would simplify deps greatly.  I was going to say "at the expense of double jar size e.g. due to webkit," but the java8 deps already come bundled with the jdk.

**Comment by vlaaad** [comment]
Please try cljfx 1.6.0 (maven dependency, not git dependency), Java 8 should be supported!
