### ISSUE TITLE
How do I select files/folders?

### ISSUE THREAD

**Issue by geokon-gh** [cljfx/cljfx#52]
Is there some built-in way to call up a file/folder-picker/chooser?

I'd like to have the user be able to click an "Open" button and then your typical file-picker dialogue shows up and you can select an image or whatever to load. Having to type out a whole path would be onerous and writing a file-picker from scratch would be a big undertaking (and it'd probably end up feeling unnatural)

Could I get your advice @vlaaad on how I should approach this? I saw that JavaFX has a FileChooser built-in. Should I just be calling this through Java interop?

**Comment by vlaaad** [comment]
Yes, you should use FileChooser using interop: it's an OS-native window, designed in a blocking fashion which does not map well to cljfx/react model. It's probably can be done the cljfx way (there is [WIP PR](https://github.com/cljfx/cljfx/pull/40)), but it works just fine using interop. There is also [an example](https://github.com/cljfx/cljfx/pull/40#issuecomment-544256262) in that PR that shows how FileChooser can be used.

**Comment by vlaaad** [comment]
Did it help you @geokon-gh ?

**Comment by geokon-gh** [comment]
Yes! It was very helpful. Thank you for checking in :)

Sorry I didn't write back. I was just testing things out and wanted to write back when my understanding was a bit less half-baked and then got lost trying to understand the selection-props/list-view stuff

I had issues with the part that reads `{:dispatch {:event/type :load-project :file file}})))`
I'm guessing this is supposed to trigger an event, but the event wouldn't trigger for me, so I changed things a bit.

``` clojure
(defmethod event-handler ::load-new-xrf-scan [_]
    (let [file (-> (doto (FileChooser.)
                     (.setTitle "Open a project")
                     (.showOpenDialog (Stage.)))]
      (swap! *state assoc :xrf-scan (load-xrf-scan file))))
```
I expect the thread/dispatch stuff was there for a reason and this will somehow blow up in my face later :)

I also.. dont know about this `(.showOpenDialog (Stage.)))]` line. I had to import `           javafx.stage.Stage` to get that working but looking at the documentation this method doesn't seem to exist: https://docs.oracle.com/javase/8/javafx/api/javafx/stage/Stage.html

Maybe this was using the Swing FilePicker? I'm not quite sure

PS: If questions aren't very appropriate for github Issues, just let me know please :)

**Comment by vlaaad** [comment]
`{:dispatch ...}` is only needed when you use [effects](https://github.com/cljfx/cljfx/#event-handling-on-steroids) for event handling. The default example of effects in the readme has only `:state` effect, but you can also add `:dispatch` effect that dispatches another event (there is `fx/dispatch-effect` for that). In short, it's a way to call your event handler again.

Regarding `showOpenDialog` — it's inside `doto`, so it's on the [FileChooser](https://openjfx.io/javadoc/12/javafx.graphics/javafx/stage/FileChooser.html#showOpenDialog(javafx.stage.Window)), not on a Stage. You probably can just pass a `nil` there instead of a new stage.

Questions are appropriate here — they help me to see where people have troubles with cljfx and I can refer to them later when someone else will have similar problems :)

**Comment by vlaaad** [comment]
I added [an example](https://github.com/cljfx/cljfx/blob/master/examples/e33_file_chooser.clj) showing file chooser usage (including `:dispatch` effects).

**Comment by geokon-gh** [comment]
Thank you for that cleaned up example
I should probably move over to using effects eventually. Just need to get a minimal working example first before I start wrapping my head around that :)

I will post here if I further issues with this. Thank you again

**Comment by vlaaad** [comment]
You don't have to use them if you do something small, it's a layer of indirection that allows decoupling from mutable atom.

**Comment by vlaaad** [comment]
Feel free to open the issue again if you'll have further questions related to FileChooser!
