### ISSUE TITLE
Enhance `:day-cell-factory` support or provide example

### ISSUE THREAD

**Issue by jdf-id-au** [cljfx/cljfx#53]
I'm trying to add a `:day-cell-factory` to a `:date-picker`. It seems that I have to `reify Callback` etc for this, in contrast to `:list-view`'s `:cell-factory`  which accepts a fn and [reifies for me](https://github.com/cljfx/cljfx/blob/0ebafe9f70bd49c03917fcdf835617c632d9c04d/src/cljfx/fx/list_view.clj#L19).

I don't quite understand enough about how the `:list-view` `:cell-factory` function arity rises from 1 (where it's defined, [e.g.](https://github.com/cljfx/cljfx/blob/master/examples/e16_cell_factories.clj#L6)) to 4 ([where it's called](https://github.com/cljfx/cljfx/blob/0ebafe9f70bd49c03917fcdf835617c632d9c04d/src/cljfx/fx/text_field_list_cell.clj#L37), in `cljfx.fx.text-field-list-cell/create`) to be able to implement the equivalent thing for `DateCell`, and so can't offer a PR.

Can you point me in the right direction?

**Edit** I found [`lifecycle/detached-prop-map`](https://github.com/cljfx/cljfx/blob/9226eebf23c444a980dfd430253ff02a9fdc9205/src/cljfx/lifecycle.clj#L216) which seems to be where the apparent arity change comes from. Will come back when have some spare time and have a go at PR...

**Comment by vlaaad** [comment]
Hi! Yes, detached-prop-map is the right direction :)

**Comment by vlaaad** [comment]
Do you have plans to make a PR? It would be much appreciated, but if not, it's okay too — I'll do it then.

**Comment by jdf-id-au** [comment]
I can, but have a deadline that needs dealing with first!

**Comment by vlaaad** [comment]
Just realized this issue is fixed by [1.7.7](https://github.com/cljfx/cljfx/blob/master/CHANGELOG.md#177---2020-08-30).
