### ISSUE TITLE
How to stop event propagation?

### ISSUE THREAD

**Issue by jpmonettas** [cljfx/cljfx#54]
Hi, first of all thanks for the amazing lib!

I have a :on-mouse-pressed defined for both a Scene and a Rectangle inside the scene. When clicking the rectangle both events handlers get called. How do I stop event bubbling up aka stopPropagation?

Thanks!!!

**Comment by vlaaad** [comment]
Hi! You need to call `consume` method on the event in the handler to stop its propagation.

**Comment by jpmonettas** [comment]
Hey thanks for the quick response!

Tried it but still doesn't work. The event shows as consumed true but both events are fired.
Here is a minimal example:

```clojure
(def app
  (fx/create-app
   (atom (fx/create-context {}))
   :event-handler (fn [{:keys [fx/event fx/context] :as evinfo}]
                    (.consume event)
                    (prn "Clicked type : " (:type evinfo) event)
                    {:context {}})
   :desc-fn (fn [_]
              {:fx/type :stage
               :showing true
               :width 800
               :height 600
               :scene {:fx/type :scene                                       
                       :on-mouse-pressed {:event/type :grab
                                          :type :scene}
                       :root {:fx/type :group                                              
                              :children [{:fx/type :rectangle
                                          :width 100
                                          :height 100
                                          :on-mouse-pressed {:event/type :grab
                                                             :type :rectangle}}]}}})))
```

**Comment by vlaaad** [comment]
Ah, I see. This is subtle: you need to consume the event before the JavaFX handler returns. Using the app makes event handling asynchronous: it's executed after JavaFX does event bubbling. You can make JavaFX event handler block until the event is processed by adding `:fx/sync true` to map event definition, like that:
```
{:event/type :grab
 :fx/sync true
 :type :rectangle}
```
This will ensure event handler execution before the event gets bubbled to parents.

**Comment by jpmonettas** [comment]
Thanks @vlaaad! That makes sense and works perfectly!

Trying to migrate this UI https://github.com/jpmonettas/clograms from re-frame to cljfx, lets see how it goes!
