### ISSUE TITLE
How to hook up a spinner to a factory?

### ISSUE THREAD

**Issue by geokon-gh** [cljfx/cljfx#61]
I'm trying to make an input cell that's just for integers and I thought a integer spinner would be perfect for that - however I can't figure out how to hook up a `integer-spinner-value-factory` to a `spinner`

I tried to find other "factory" based code and I found this example:
https://github.com/cljfx/cljfx/blob/30a8c71d5bab559a733e4bb19d1412ef1227b0f5/examples/e16_cell_factories.clj

But all the elements have a `:cell-factory` key for the factory to be hooked up to. Is there any way you could maybe add an example? Thank you for the wonderful library as always. I've been using it regularly the past couple of months and it beats everything else for making native GUIs

**Comment by vlaaad** [comment]
Hi! Cell factories in examples you linked showcase functions that return component descriptions, but in case of a spinner, it's different, although it's also called a factory.

Value factory on a spinner is just a regular component, you can describe it like that:
```clj
{:fx/type :spinner
 :value-factory {:fx/type :integer-spinner-value-factory
                 :min 0 
                 :max 100}}
```

Thank you for your kind words and you are welcome :)

**Comment by geokon-gh** [comment]
I somehow missed that. And how do I then hook up an event to the track the changing value ? :sweat_smile: 

https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Spinner.html#editorProperty--

It seems I need to access the "Editor" Textfield and bind an event to the :on-action hook. But I don't understand how to access elements like that within the data-driven model of CLJFX

**Comment by vlaaad** [comment]
Hmm, that's a bit more involved: you'll need to create a prop for observing these changes:
```clj
(require '[cljfx.prop :as fx.prop]
         '[cljfx.mutator :as fx.mutator]
         '[cljfx.lifecycle :as fx.lifecycle])

(import '[javafx.scene.control Spinner])

(def ext-with-spinner-props
  (fx/make-ext-with-props
    {:on-spinner-text-changed (fx.prop/make (fx.mutator/property-change-listener
                                              #(.textProperty (.getEditor ^Spinner %)))
                                            fx.lifecycle/change-listener)}))

(fx/on-fx-thread
  (fx/create-component
    {:fx/type :stage
     :showing true
     :scene {:fx/type :scene
             :root {:fx/type ext-with-spinner-props
                    :props {:on-spinner-text-changed prn}
                    :desc {:fx/type :spinner
                           :value-factory {:fx/type :integer-spinner-value-factory
                                           :min 0
                                           :max 10}}}}}))
```

**Comment by geokon-gh** [comment]
Sorry for the slow reply. Thank you for this. I'd hack in something workable with the `:text-input-field`. I tried to switch to your spinner b/c it's a bit better at first blush, but it will still "passes through" everything you type in to the event handler (like numbers from outside the range). It also blows up if you input text and hit enter. So in the end either way I'm stuck massaging/validating input :)

But thank you for showing how it's done! Much appreciated

**Comment by vlaaad** [comment]
Hey, I just had a look at Spinner's javadoc, and it has read-only value property that can be observed similarly, maybe that's what you want?

**Comment by vlaaad** [comment]
Hey @geokon-gh!
I just wanted to let you know that [1.6.8](https://github.com/cljfx/cljfx/blob/master/CHANGELOG.md#168---2020-04-10) just got released that adds support for observing spinner value changes, like that:
```clj
{:fx/type :spinner
 :value-factory {:fx/type :integer-spinner-value-factory
                 :min 0
                 :max 10
                 :value 5
                 :on-value-changed prn}}
```
or alternatively, on `:spinner` itself:
```clj
{:fx/type :spinner
 :value-factory {:fx/type :integer-spinner-value-factory
                 :min 0
                 :max 10
                 :value 5}
 :on-value-changed println}
```

**Comment by geokon-gh** [comment]
Oh great! It's on my TODO list :))

**Comment by geokon-gh** [comment]
It works great and it's much better than what I had implemented manually. I still need an additional input validation step but it's fine

There is just one minor issue. If you enter a non-valid number (outside the range) then the spinner will gracefully handle the situation. But if you input a string then you get an uncatchable exception:

```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.text.ParseException: Unparseable number: "f118"
	at javafx.scene.control.SpinnerValueFactory$DoubleSpinnerValueFactory$1.fromString(SpinnerValueFactory.java:720)
	at javafx.scene.control.SpinnerValueFactory$DoubleSpinnerValueFactory$1.fromString(SpinnerValueFactory.java:692)
```
The app keeps running and my event isn't called, so it "works" but I do get a stack dump on the console

**Comment by vlaaad** [comment]
Not sure I can do anything about that — this seems to be a JavaFX issue. I know there is another way to input numbers that might be useful: [text formatter](https://github.com/cljfx/cljfx/blob/master/examples/e29_text_formatter.clj#L27-L31). It does not allow limiting numbers to a range, but I don't remember it throwing exceptions when I tried typing invalid numbers.

**Comment by geokon-gh** [comment]
I finally got around to using a text-formatter and a text-field and the result is much cleaner. Thank you for the pointer @vlaaad ! It does lack the little buttons and up/down arrow adjustments, but it's a small loss

Appreciate your insight and help as always
