### ISSUE TITLE
AOT stalls with only cljfx.api required

### ISSUE THREAD

**Issue by joinr** [cljfx/cljfx#63]
following the reddit thread [here](https://www.reddit.com/r/Clojure/comments/fw93gc/new_clojurians_ask_anything/fms5bkq/?context=3) 

user geokon failed to aot compile an uberjar with a main class, compilation stalled overnight.  further dissection led to discovering that the require for cljfx.api caused a stall during AOT compilation, but not at the REPL.  

[minimal reproducible example repo](https://github.com/joinr/cljfxaot)

Hypothesis is that there's some deadlock happening in the javafx thread and initialization that's being tripped over during AOT compilation.  This is on java 1.8 on my setup, no idea off the original user's.  Seems odd since vlaad is apparently able to AOT stuff enough to get graal native image going....

**Comment by joinr** [comment]
User was able to get past this using deps tooling [cambada](https://github.com/luchiniatwork/cambada) to build an uberjar that AOT compiles and launches from main.  So, may be a lein issue and not cljfx in particular.

**Comment by vlaaad** [comment]
Hi!
Cljfx starts a non-daemon JavaFX application thread, which is unfortunately needed for AOT compilation (I explained [here](https://github.com/cljfx/cljfx/issues/17#issuecomment-493705534) why). The solution is to compile and then call `(javafx.application.Platform/exit)` (or `(System/exit 0)`).

It looks like cambada [does that](https://github.com/luchiniatwork/cambada/blob/c07bf321e2fc2948fb11a2fb7bbe7d2a4be10463/src/cambada/cli.clj#L122), while lein uberjar [doesn't](https://github.com/technomancy/leiningen/blob/master/src/leiningen/compile.clj).

**Comment by joinr** [comment]
thanks for the specifity, I had no idea of this corner case.

**Comment by vlaaad** [comment]
I spent a lot of time figuring that out 😬

**Comment by joinr** [comment]
fwiw, the lein work arounds mentioned in the other issue thread did not work for me (I got the same error complaining that the platform exit had been called).  Curious if this is something to be solved at the leiningen level via plugin or something (hacky but better than nothing), or if lein could be more like cambada without breaking anything.

**Comment by vlaaad** [comment]
I have a feeling that might be because on java 8 javafx initialization and shutdown code is different from the java 11 one, so injecting `Platform/exit` on java 8 might not work, while working on java 11. I wonder if lein injections happen before or after compilation...

**Comment by geokon-gh** [comment]
Is this also why `depstar` hangs?

Unlike with `cambada` it gives me huge dump of warnings
``` clojure
;;  .....
{:warning "clashing jar item", :path "com/sun/javafx/css/StyleManager.class", :strategy :noop}
{:warning "clashing jar item", :path "com/sun/javafx/css/PseudoClassState.class", :strategy :noop}
{:warning "clashing jar item", :path "com/sun/javafx/css/FontFaceImpl$FontFaceSrc.class", :strategy :noop}
{:warning "clashing jar item", :path "com/sun/javafx/css/Combinator$1.class", :strategy :noop}
{:warning "clashing jar item", :path "com/sun/javafx/css/StyleManager$StylesheetContainer.class", :strategy :noop}
{:warning "clashing jar item", :path "com/sun/javafx/css/parser/Token.class", :strategy :noop}
;; . ..... etc
Processing pom.xml for {sausage/sausage {:mvn/version "1.0.0-SNAPSHOT"}}
```
And then it hangs
It does however produce a working .jar that is only different by a few kilobytes from the `cambada` one (I should diff the two :))

**Comment by vlaaad** [comment]
Yes, it also hangs because it doesn't exit when completing compilation. It's not failing to compile, it's just keeps jvm running after finishing the job. Regarding clashing  javafx classes: are you by any chance using jdk 11 that bundles javafx? I would suggest against doing so: javafx was rightfully removed from the jdk — it's just a library after all, and it is included by cljfx as a library via normal maven dependency.

**Comment by geokon-gh** [comment]
I don't think my jdk bundles it. It's the one from the the ubuntu repository `openjdk-11-jre` (well now also `openjdk-11-jdk` but I'm trying to get proguard to cooperate..) but there seems to be a separate `openjfx` package which i don't have installed.

Again, I wasn't seeing these same warnings through `cameba` though i guess it could be hiding/suppressing them. I'm also not sure this is `cljfx` related. I'd need to try a minimal example

**Comment by vlaaad** [comment]
Oh, it also could be the case if you include all platform classifiers when depending on javafx to include all platform-specific libraries — I guess both `javafx.graphic$linux` and `javafx.graphics$mac` could include class files and depstar just complains about that.

**Comment by vlaaad** [comment]
By the way, if you want to keep using depstar, you can create your own build file, it's very easy with tools-deps:
1. You add an alias to depstar, but specify your own main:
   ```clj
   :depstar {:extra-deps {seancorfield/depstar {:mvn/version "0.5.2"}}
             :extra-paths ["build"]
             :main-opts ["-m" "uberjar"]}
   ```
2. You create a folder `build`, and there you create a file `uberjar.clj` (that's the file specified in alias) with the following contents:
   ```clj
   (ns uberjar
     (:require [hf.depstar.uberjar :as depstar])
     (:import [javafx.application Platform]))
   
   (defn -main []
     (depstar/-main "sausage.jar" "--compile" "-m" "sausage.core")
     (Platform/exit))
   ```

**Comment by geokon-gh** [comment]
Thanks! `cambada` seems to work just fine for now. It's just no longer maintained unlike `depstar`, but I don't have any specific complaints. I'll make sure to come back to this when it starts showing issue though :))

I'm keeping some notes here: https://geokon-gh.github.io/clojure-packaging.html
And added a link to your fix there.

Maybe an issue on `depstar` would be in order?

That said.. if I want to try packaging with `jlink`/`jpackage` then switching to `depstar` and then copying your Github Actions from [hn](https://github.com/cljfx/hn/blob/master/.github/workflows/build-release-artifacts.yml) would probably make my life a bit easier (I think I might be able to just drop in your configuration and have it work.. but tell me if I'm wrong)

**Comment by vlaaad** [comment]
It's not enough to just copy configuration, you will need to create personal access token that has the rights to create releases and add it as a secret to your repo and use it create releases. That's because release artifacts are generated as a response to "create release" github event that is triggered by another github action that is executed on tag push, but that release event can't be dispatched by default with an access token that is used by github actions by default — it can create a release, but it does not trigger another build.

**Comment by vlaaad** [comment]
[1.7.0](https://github.com/cljfx/cljfx/blob/master/CHANGELOG.md#170---2020-05-04) has a solution for this problem.
