### ISSUE TITLE
How to make a context menu?

### ISSUE THREAD

**Issue by geokon-gh** [cljfx/cljfx#71]
Hey vlaaad, I'm just really unsure what the proper way to do this is.

I'd like to add context menus in my GUI but the way JavaFX goes about this is a bit bizarre.
You can attach a context menu in a straightforward way to a "control" nodes b/c there is an associated `:context-menu` property. 

However in general nodes this property doesn't exist for whatever reason. Instead they have  a `:on-context-menu-requested` prop. You can attach a listener/effect/event-handler and it triggers with  a `javafx.scene.input.ContextMenuEvent`. This has an X/Y poistion.. so I could then track if a menu was opened and then add a context menu to be displayed at that location etc. etc.  .. but it seems rather clunky. I need to then track where/when menus are opened in my state somewhere

I get the sense it's not the way to do it but I can't figure out what the API design expects me to do :)

**Comment by vlaaad** [comment]
Hi! 

Unfortunately, I'm just following a JavaFX decision to make context menus available only on controls by default — I think they made it this way to not create a dependency from basic Nodes to Controls (which are different modules). Implementing context menus on other nodes IS clunky, but it is possible to create a custom prop that will have a mutator that sets a listener on an onContextMenuRequest property and shows a context menu:

```clj

(defn- context-menu->listener [^ContextMenu menu]
  (reify EventHandler
    (handle [_ e]
      (let [^ContextMenuEvent e e]
        (.show menu ^Node (.getTarget e) (.getScreenX e) (.getScreenY e))))))

(def ext-with-context-menu
  (fx/make-ext-with-props
    {:context-menu (prop/make
                     (mutator/setter #(.setOnContextMenuRequested ^Node %1 %2))
                     (lifecycle/wrap-coerce lifecycle/dynamic context-menu->listener))}))

;; example usage
{:fx/type ext-with-context-menu
 :props {:context-menu {:fx/type :context-menu
                        :items [{:fx/type :menu-item
                                 :text "hello"}]}}
 :desc {:fx/type :text
        :text "I am not a control!"}}
```
