### ISSUE TITLE
nil's in :children cause IllegalArgumentException

### ISSUE THREAD

**Issue by Folcon** [cljfx/cljfx#74]
So I got this:
```clojure
java.lang.IllegalArgumentException: No implementation of method: :create of protocol: #'cljfx.lifecycle/Lifecycle found for class: nil
```
Not certain this is something I'm doing wrong, or if it's something not done by the underlying lib, but personally in my experience being able to do this sort of this is really useful:
```clojure
{:fx/type :v-box
  :children [(when (get-in @*state [:state :chart-data])
               (render-chart (get-in @*state [:state :chart-data])))]}
```

It's easy enough to wrap them in functions if you'd rather not support this however =)...

**Comment by vlaaad** [comment]
Hi!
This is intended: `nil` is not a valid component description, and cljfx is not trying to be smart with skipping nils or flattening lists because end-user might want to extend nils or lists to their own lifecycles. I would recommend doing something like this:
```clj
{:fx/type :v-box
 :children (if (get-in @*state [:state :chart-data])
             [(render-chart (get-in @*state [:state :chart-data]))]
             [])}
```

**Comment by vlaaad** [comment]
Another way to add children optionally is using `cond->` with `conj`:
```clj
(cond-> []
  (get-in @*state [:state :chart-data])
  (conj (render-chart (get-in @*state [:state :chart-data]))))
```
This way it's possible to add multiple optional children.

**Comment by Folcon** [comment]
Ok, just curious, is there an equivalent of a noop? I've been wondering if I could use:
```
{:fx/type :label :text ""}
```

**Comment by vlaaad** [comment]
It's not a complete noop — it's still a node in a display graph. Placing it in a v-box with some spacing will add additional spacing, for example. I would say, the absence of a node in a list of children is the best noop, but your suggestion is fine too in certain cases. You don't need to specify text as it's empty by default.

**Comment by Folcon** [comment]
Ok, thanks!

I'll use the `cond->` form a bit, I'm just really used to the where form I mentioned earlier...

I've also been musing about wrapping this and re-frame so I can have 1 UI description layer which then nicely falls out for my application, but I might be being naive =)...

**Comment by vlaaad** [comment]
You can use `concat`, which is closer to the form you are used to:
```clj
(concat 
  (when (get-in @*state [:state :chart-data])
    [(render-chart (get-in @*state [:state :chart-data])))]))
```

I think JavaFX and web UI semantics are very different, so ensuring that behavior is the same will be quite a big task...

**Comment by Folcon** [comment]
That's fair and thanks for the example =)...
