### ISSUE TITLE
Document Tooltips with Charts

### ISSUE THREAD

**Issue by Folcon** [cljfx/cljfx#75]
I've been rendering some pie charts and wanted to work out how I can customise them =)...

I've rendered these two and as you can see the right one doesn't have any labels or legend being generated.
<img width="466" alt="Screenshot 2020-06-05 at 12 58 53" src="https://user-images.githubusercontent.com/123055/83874089-d7d9db80-a72c-11ea-9f30-db26169af954.png">

I thought as a reasonable workaround I could try and at the very least provide a tooltip on hover, but following your instructions for adding tooltips doesn't appear to work.

```clojure
(defn pie-chart [title slices]
  {:fx/type :pie-chart
   :title (str title)
   :data (mapv (fn [[label slice]]
                 {:fx/type fx.ext.node/with-tooltip-props
                  :props {:tooltip {:fx/type :tooltip :text "Test Tooltip"}}
                  :desc {:fx/type :pie-chart-data :name (str label) :pie-value slice}}) slices)})
```
gives:
```clojure
java.lang.ClassCastException: class javafx.scene.chart.PieChart$Data cannot be cast to class javafx.scene.Node (javafx.scene.chart.PieChart$Data and javafx.scene.Node are in unnamed module of loader 'app')
```

```clojure
(defn pie-chart [title slices]
  {:fx/type :pie-chart
   :title (str title)
   :data (mapv (fn [[label slice]]
                 {:fx/type :pie-chart-data :name (str label) :pie-value slice
                  :tooltip {:fx/type :tooltip
                            :text "I am a tooltip!"}}) slices)})
```
gives:
```clojure
clojure.lang.ExceptionInfo: No such prop: :tooltip {:prop :tooltip}
```

I'm currently trying to unpack [this java code](https://stackoverflow.com/a/25906039) to see if I can understand what it's doing and work from that side =)...

**Comment by vlaaad** [comment]
Hi! There is a very big difference between pie charts, that are almost completely uncustomizable, and line charts you linked that are customizable. In short — there is no way to add tooltips on pie charts in cljfx because there is no way to add tooltips to pie charts in javafx.

Line chart (and other xy-charts), on the other hand, allow setting custom nodes for their data points, and that can be used to add tooltips.

Example of line-chart with tooltip:
```clj
(fx/on-fx-thread
  (fx/create-component
    {:fx/type :stage
     :showing true
     :scene {:fx/type :scene
             :root {:fx/type :line-chart
                    :x-axis {:fx/type :number-axis}
                    :y-axis {:fx/type :number-axis}
                    :data [{:fx/type :xy-chart-series
                            :data [{:fx/type :xy-chart-data
                                    :x-value 1
                                    :y-value 1
                                    ;; pie chart data does not have this:
                                    :node {:fx/type fx.ext.node/with-tooltip-props
                                           :props {:tooltip {:fx/type :tooltip :text "Test tooltip"}}
                                           :desc {:fx/type :region}}}]}]}}}))
```

I don't know what causes another pie chart to have no label or legend, can you share a repro?

**Comment by Folcon** [comment]
Oh, thanks for the heads up, I didn't realise that =)...

I think the below works as a minimal repro?

```clojure
(def *state
  {:title "Sim"
   :world {:stats {:religion {:none 5000}, :gender {:female 2500, :male 2500}, :job {nil 3000, :light 1019, :heavy 981}, :hometown {:manchester 433, :leeds 434, :glasgow 446, :liverpool 472, :sunderland 455, :newcastle 480, :sheffield 502, :bradford 426, :london 467, :wolverhampton 442, :birmingham 443}, :race {#{:human} 5000}, :beliefs {}}}})

(defn pie-chart [title slices]
  {:fx/type :pie-chart
   :title (str title)
   :data (mapv (fn [[label slice]]
                 {:fx/type :pie-chart-data :name (str label) :pie-value slice}) slices)})

(defn render-peep-stats [stats]
  {:fx/type :h-box
   :children (mapv
               (fn [[title slices]]
                 (pie-chart title slices))
               stats)})

(defn root-view [{:keys [title]}]
  {:fx/type :stage
   :showing true
   :always-on-top true
   :title title
   :scene {:fx/type :scene
           :on-key-pressed {:event/type :event/scene-key-press}
           :root {:fx/type :v-box
                  :children [(render-peep-stats (get-in @*state [:world :stats]))]}}})
```

Produces this:
<img width="1434" alt="Screenshot 2020-06-06 at 13 37 12" src="https://user-images.githubusercontent.com/123055/83944360-de368900-a7fa-11ea-97fa-494ef9cdcf1f.png">

I'd expect the pie chart to shrink?

**Comment by vlaaad** [comment]
I find it interesting that on my machine your example shows labels on a hometown pie chart:
![Screenshot from 2020-06-07 11-44-36](https://user-images.githubusercontent.com/732554/83965481-59a84100-a8b4-11ea-8679-2b9c072b34df.png)

It looks like something javafx-related, and I don't know what's happening here. I can suggest experimenting with setting a minimum size on charts — maybe that'll help? Like setting `:min-width 500 :min-height 500` on a `:pie-chart`?

**Comment by vlaaad** [comment]
Accidentally closed. Please comment if you find a workaround for future readers :)

**Comment by Folcon** [comment]
It's not obvious that's for sure =)...

Setting `:max-width 100 :max-height 100` breaks more of the pie-charts...

<img width="787" alt="Screenshot 2020-06-09 at 23 25 50" src="https://user-images.githubusercontent.com/123055/84207195-b2d8c600-aaa8-11ea-9315-4b2e4488fe9d.png">

I did [find this](https://stackoverflow.com/a/29511403):
```
// Code from PieChart.java
if(!shouldShowLabels) {
     pieRadius = Math.min(contentWidth,contentHeight) / 2;
}
```

But I tried fiddling with max/min numbers like it suggested and couldn't quite get it to work...

However [this led me to](https://stackoverflow.com/a/58262959) *a* right answer:
```
".chart" {:-fx-pref-width 343 #_229
                 :-fx-pref-height 323 #_155
                 :-fx-min-width 343
                 :-fx-min-height 323
                 :-fx-max-width 343
                 :-fx-max-height 323}

 ".chart-content" {:-fx-padding "20px"}
```
<img width="1296" alt="Screenshot 2020-06-09 at 23 39 36" src="https://user-images.githubusercontent.com/123055/84208113-e61c5480-aaaa-11ea-93f2-aed5d9577078.png">

The reason I say a right answer is that you have to figure out what the "magic" numbers are. It's really a fragile solution, but I'm getting the impression that we can't really improve on it without reimplementing how it computes the render logic?

**Comment by vlaaad** [comment]
Haha, wow!

> I'm getting the impression that we can't really improve on it without reimplementing

Sadly I found this to be true of many different parts of JavaFX.

Thanks for sharing!
