### ISSUE TITLE
Barchart syncs until it doesn't

### ISSUE THREAD

**Issue by Folcon** [cljfx/cljfx#76]
Hey,
I'm starting to feel a bit bad for all the issues I'm making 😞.

So I've got this:
```clojure
(defn goods-sales [stores]
  (let [goods (into [] (comp (map (juxt :short-name :cost :quantity)) (map (fn [[short-name cost quantity]] (println short-name cost quantity) {:fx/type :xy-chart-data :x-value (if (neg? quantity) (- quantity) quantity) :y-value (str short-name "- " cost " cp")}))) (take 10 (sort-by :quantity (mapcat :goods stores))))]
    {:fx/type :v-box
     :children
     [{:fx/type :text-area :text (pr-str goods)}
      {:fx/type :bar-chart
       :title "Shop Sales"
       :x-axis {:fx/type :number-axis}
       :y-axis {:fx/type :category-axis}
       :data [{:fx/type :xy-chart-series
               :data goods}]}]}))
```

Which mirrors your example I believe:
```clojure
(def bar-chart
  {:fx/type :bar-chart
   :title "Top headline phrases"
   :legend-visible false
   :x-axis {:fx/type :number-axis}
   :y-axis {:fx/type :category-axis}
   :data [{:fx/type :xy-chart-series
           :data [{:fx/type :xy-chart-data :x-value 8961 :y-value "will make you"}
                  {:fx/type :xy-chart-data :x-value 4099 :y-value "this is why"}
                  {:fx/type :xy-chart-data :x-value 3199 :y-value "can we guess"}
                  {:fx/type :xy-chart-data :x-value 2398 :y-value "only X in"}
                  {:fx/type :xy-chart-data :x-value 1610 :y-value "the reason is"}
                  {:fx/type :xy-chart-data :x-value 1560 :y-value "are freaking out"}
                  {:fx/type :xy-chart-data :x-value 1425 :y-value "X stunning photos"}
                  {:fx/type :xy-chart-data :x-value 1388 :y-value "tears of joy"}
                  {:fx/type :xy-chart-data :x-value 1337 :y-value "is what happens"}
                  {:fx/type :xy-chart-data :x-value 1287 :y-value "make you cry"}]}]})
```

Now I have some simple app state that is manipulated by UI buttons on the window.

Now if I initialise the chart it works fine:
<img width="792" alt="Screenshot 2020-06-16 at 19 11 07" src="https://user-images.githubusercontent.com/123055/84812288-15304a00-b006-11ea-97e2-bbadf0a3ead1.png">

If I update the chart it works fine (did it twice to show no issues):
<img width="798" alt="Screenshot 2020-06-16 at 19 11 23" src="https://user-images.githubusercontent.com/123055/84812334-2aa57400-b006-11ea-9bb4-53879cd0803e.png">

<img width="795" alt="Screenshot 2020-06-16 at 19 11 31" src="https://user-images.githubusercontent.com/123055/84812380-3e50da80-b006-11ea-8486-d6f60e8ceb4e.png">

Now if I reinitialise the data it breaks (you can see the names / costs have changed in the text area), the x-axis is at zero though! The y-axis still has the old data:
<img width="795" alt="Screenshot 2020-06-16 at 19 11 41" src="https://user-images.githubusercontent.com/123055/84812454-59bbe580-b006-11ea-8364-a9c236bd5a41.png">

And if I update this chart, the bars+y-axis is still broken, but the x-axis has updated:
<img width="793" alt="Screenshot 2020-06-16 at 19 11 53" src="https://user-images.githubusercontent.com/123055/84812616-92f45580-b006-11ea-8bc4-a8cd468fc5db.png">

Calling `renderer` fixes it, but I don't think that's the solution?:
```clojure
(defonce renderer
  (fx/create-renderer
    :middleware
    (fx/wrap-map-desc (fn [state]
                        {:fx/type root-view
                         :state state}))
    :opts {:fx.opt/map-event-handler event-handler}))
```

At least I don't believe I should be calling the `renderer` whenever I press a button?

I am wondering if I should look at something else for charting? There seems to be a bunch of problems with the javafx charting stuff? I was thinking of looking into [xchart](https://knowm.org/how-to-embed-xchart-into-a-javafx-application/)?

---
So trying a simple first stab at it [based on this](https://github.com/cljfx/cljfx/blob/master/examples/e21_extension_lifecycles.clj#L29):

deps:
```clojure
com.hypirion/clj-xchart {:mvn/version "0.2.0"}
org.openjfx/javafx-swing {:mvn/version "15-ea+6"}
```
Code:
```clojure
(require '[com.hypirion.clj-xchart :as c])
(import '[org.knowm.xchart XChartPanel])
(import '[javafx.embed.swing SwingNode])
(import '[javax.swing JPanel])

(defn xchart [_]
  (let [chart
        (c/xy-chart {"Expected rate" [(range 10) (range 10)]
                     "Actual rate" [(range 10) (map #(+ % (rand-int 5) -2) (range 10))]})
        chart-panel ^JPanel (XChartPanel. chart)
        swing-node #(doto (SwingNode.)
                      (.setContent chart-panel))]
    {:fx/type fx/ext-instance-factory
     :create swing-node}))

{:fx/type xchart} ;; <-- Stick this anywhere!
```

This works like magic! At least for rendering something, not sure if updating works, will experiment  with that next =)... Also not certain just yet how to control sizing like this lets you do or if there's an elegant way to get the styling to propagate through:
```clojure
(defn ext-instance-factory-example [_]
  {:fx/type fx/ext-instance-factory
   :create #(doto (Region.)
              (.setPrefWidth 20)
              (.setPrefHeight 20)
              (.setStyle "-fx-background-color: green;"))})
```

Not sure if generally being able to pull in swing stuff would be cool or not, still wrapping my head around what needs to be done to make it work...

---

Ok it does update, which is good, there's a bit of an ugly black screen thing going on, but frankly that's better that nothing =)... At least the charting works!

Refactored it a little so I could just drop it in:
```clojure
(defn xchart [stats]
  (let [nums (vec (shuffle stats))
        chart
        (c/xy-chart {"Expected rate" [(range (count nums)) nums]
                     "Actual rate" [(range 10) (map #(+ % (rand-int 5) -2) (range 10))]})
        chart-panel ^JPanel (XChartPanel. chart)
        swing-node #(doto (SwingNode.)
                      (.setContent chart-panel))]
    {:fx/type :v-box
     :children [{:fx/type :text-area :text (pr-str nums)}
                {:fx/type fx/ext-instance-factory
                 :create swing-node}]}))
```

Now it can just be called like so:
```clojure
(def stats [467 444 2497 487 5000 3000 969 1031 461 442 484 440 438 2503 440 5000 460 437])
(xchart stats)
```

If you know how to stop the black screen on rerender or how I could control sizing / pass on styling that would be good, but for the moment this is looking like a viable approach!

I'll try and see if I can work out how to make the xchart stuff declarative as well, still only scratching the surface of how you've put together the lib =)...

**Comment by vlaaad** [comment]
Hi @Folcon! This looks like the same problem as in #68. I spent some time and came up with a workaround.

## Problem
JavaFX can't gracefully handle setting chart series' data to a new list that contains the same instances of chart data as the previous one. Cljfx does this when it detects that the child list is changed (this happens when new chart data is added or removed, or when chart data items are reordered with `:fx/key`).

## Workaround
A workaround is to recreate a chart instance when chart data is changed. To do this gracefully one should create an extension lifecycle that recreates its child when some input data is changed.

### Extension lifecycle
```clj
(def ext-recreate-on-key-changed
  "Extension lifecycle that recreates its component when lifecycle's key is changed
  
  Supported keys:
  - `:key` (required) - a value that determines if returned component should be recreated
  - `:desc` (required) - a component description with additional lifecycle semantics"
  (reify fx.lifecycle/Lifecycle
    (create [_ {:keys [key desc]} opts]
      (with-meta {:key key
                  :child (fx.lifecycle/create fx.lifecycle/dynamic desc opts)}
                 {`fx.component/instance #(-> % :child fx.component/instance)}))
    (advance [this component {:keys [key desc] :as this-desc} opts]
      (if (= (:key component) key)
        (update component :child #(fx.lifecycle/advance fx.lifecycle/dynamic % desc opts))
        (do (fx.lifecycle/delete this component opts)
            (fx.lifecycle/create this this-desc opts))))
    (delete [_ component opts]
      (fx.lifecycle/delete fx.lifecycle/dynamic (:child component) opts))))
```
### Example usage
```clj
(def renderer (fx/create-renderer))

(defn- my-chart [{:keys [data]}]
  {:fx/type ext-recreate-on-key-changed
   :key (count data) ;; use only a count instead of the whole data since we don't reorder
   :desc {:fx/type :line-chart
          :x-axis {:fx/type :number-axis}
          :y-axis {:fx/type :number-axis}
          :data [{:fx/type :xy-chart-series
                  :data (for [[x y] data]
                          {:fx/type :xy-chart-data
                           :x-value x
                           :y-value y})}]}})

;; create and show a chart:
(renderer
  {:fx/type :stage
   :showing true
   :scene {:fx/type :scene
           :root {:fx/type my-chart
                  :data [[0 0] [1 1] [2 1] [3 2]]}}})

;; updating chart values keeps the same chart
(renderer
  {:fx/type :stage
   :showing true
   :scene {:fx/type :scene
           :root {:fx/type my-chart
                  ;; note that this vector's 3rd coordinate is different
                  :data [[0 0] [1 1] [2 0] [3 2]]}}})

;; updating chart data count does not trigger the bug anymore
(renderer
  {:fx/type :stage
   :showing true
   :scene {:fx/type :scene
           :root {:fx/type my-chart
                  :data [[0 0] [1 1] [3 2]]}}})
```

Does this workaround work for your use case?

**Comment by Folcon** [comment]
Hi @vlaaad, it does. Thanks a lot! =)...

Would it be correct that this fixes the issue of chart updating in general? As it essentially reinitialises the chart on data change?

The only thing I've noticed is that sometimes when triggering `renderer` when I'm developing at the repl my application hangs, I'm not certain if it's new behaviour or not. I'll see if I can pin down where it's happening.

**Comment by vlaaad** [comment]
Glad that it worked for you :)

Regarding hangs — do you perhaps have exception stacktraces in your repl process's stderr? Since they originate from JavaFX thread, they are not always shown in the default repl output panel.

**Comment by vlaaad** [comment]
I wouldn't say this extension lifecycle fixes the issue in general. Fixing the issue for real will require changes to JavaFX — this is a workaround :)

**Comment by challmand** [comment]
> I wouldn't say this extension lifecycle fixes the issue in general. Fixing the issue for real will require changes to JavaFX — this is a workaround :)

Great that works! I looked a that post before seeing this, but i guess I missed the context that it was related to this. 

For the :key, is this a uniq key? the example says to just use count, but if I update the data by removing and adding they could have different :desc values, I just passed in the whole data value. Would there be a reason to not do this, or use a different one? Maybe create a :key based on the sha of the data values?

**Comment by vlaaad** [comment]
The problem with charts in JavaFX seems to be triggered when the data coll of the chart is changed. Unless you use `:fx/key` on individual data descriptions, it will only happen when the count of items changes, otherwise existing data objects will be updated instead, so `count` should be enough.

The `:key` of `ext-recreate-on-key-changed` is only used to signal that we should re-create the `:desc` from scratch instead of updating it over the lifetime of the component, there are no special uniqueness requirements.

**Comment by CoutCesar** [comment]
It can be easily solved by disabling the chart animations with chart.setAnimated(false);
