### ISSUE TITLE
Can't create uberjar

### ISSUE THREAD

**Issue by pouya-abbassi** [cljfx/cljfx#77]
Hello there.
I've been trying cljfx for some simple applications and it works just fine while developing (emacs+cider). However I can't create uberjar.
When i run `lein uberjar` the terminal stops at `Compiling cljfx-test.core` and doesn't go any further.
No excessive CPU or RAM usage, and no errors.

I use `cljfx "1.7.3"` and `clojure "1.10.0"`
and:
```
─$ java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)

─$ lein version
OpenJDK 64-Bit Server VM warning: forcing TieredStopAtLevel to full optimization because JVMCI is enabled
Leiningen 2.9.1 on Java 11.0.6 OpenJDK 64-Bit Server VM

```

Can you please help my identify and fix the problem?

**Comment by vlaaad** [comment]
Hi! Looks like a known issue — compilation requires javafx to be running — that has existing solution: see [aot](https://github.com/cljfx/cljfx#aot-compilation-is-complicated) readme section. Does this work for you?

**Comment by vlaaad** [comment]
See also: [previous discussion](https://github.com/cljfx/cljfx/issues/17) for context and more info

**Comment by pouya-abbassi** [comment]
Yes! Thanks a lot.
Sorry, I should've read more carefully :)

How about GraalVM? Does it also have a workaround? Because I can't create native-image.
Seems like most of Clojure libraries are not suitable for native-image. Or maybe it's something I'm missing here.

**Comment by vlaaad** [comment]
Glad you got it working!

I tried a couple of times but ultimately didn't have any success with GraalVM. I know a couple of other people tried too, and I think [this](https://github.com/michaelsbradleyjr/hello-cljfx-native) project is the only one that got it somewhat working. If you want to try as well, I'd suggest having a look at that repo. There is also my [unsuccessful experiment](https://github.com/cljfx/hn/blob/native-image/build/native_image.clj) with a write-up. One important note is that you can't use the default GraalVM distribution, instead, you will need [GlounHQ's fork](https://github.com/gluonhq/client-samples) that has some changes to make it work with JavaFX.
