### ISSUE TITLE
Can reframe's `dispatch-n` be added?

### ISSUE THREAD

**Issue by den1k** [cljfx/cljfx#81]
https://github.com/day8/re-frame/blob/f289dec566f9253eeaf722d441e6dc6bdfbc5d85/src/re_frame/fx.cljc#L97-L115

Either as part of the internal library or as middeware for event-handlers

**Comment by vlaaad** [comment]
Cljfx's `wrap-effects` does not require you to return a map. It accepts both maps:
```clj
{:dispatch {:event/type ::my-event}}
```
and colls
```clj
[[:dispatch {:event/type ::my-event}]
 [:dispatch {:event/type ::other-event}]]
```
So there is no need for separate `dispatch-n`
