### ISSUE TITLE
Middleware to allow nil values

### ISSUE THREAD

**Issue by den1k** [cljfx/cljfx#82]
Reagent, re-frame and uix allow nil values as children of components. Allowing `nil`s is valuable for conditional renders, e.g.

```clojure
[:div.nav (when (logged-in? user) [nav-user-avatar-button])]
```

By default `nil`s error in CLJFX with cljfx.api/create-app:

```
java.lang.IllegalArgumentException: No implementation of method: :create of protocol: #'cljfx.lifecycle/Lifecycle found for class: nil
```

Is there a way to skip nils in CLJFX?

**Comment by vlaaad** [comment]
See my previous response to a question about handling conditional nodes: https://github.com/cljfx/cljfx/issues/79#issuecomment-661824147
There is no built-in way to skip `nil`s, and since users can extend Lifecycle protocol to any values, introducing this would be a breaking change.

**Comment by den1k** [comment]
I checked out the other issue. I have been using the workaround you described, however given how common conditionals are using `cond->`/`concat` worsens readability of the code. So I'm thinking could this be an optional middleware? Then it wouldn't be a breaking change. Maybe renderer could take an optional predicate function or transducer that it uses as it is traversing the component tree to ignore certain items?

**Comment by vlaaad** [comment]
Ah, I see. I'm afraid middleware won't help here — handling of props that correspond to collections of components is defined in props themselves, and cljfx does not have any overridable layer of indirection there.

**Comment by den1k** [comment]
If you think this is possible and would be open to PR please let me know ;)
