### ISSUE TITLE
Getting text from text field on focus changed [question]

### ISSUE THREAD

**Issue by jdf-id-au** [cljfx/cljfx#86]
Hi and thank you again for a glorious library.

I'm trying to fire an event when a text field loses focus, such that the text field's content is included in the event.

I can only get the field's content via `:on-text-changed` and `:on-action`. The former is too spammy and the latter needs the user to hit enter. However, `:on-focused-changed` only gives a boolean (because it's a `:property-change-listener`).

I can't quite work out how to get `:on-focused-changed` to pass the event rather than the boolean.

What is the best approach for this?

**Comment by vlaaad** [comment]
Are you trying to do sort of a form with multiple inputs? There is another approach that might be useful for UI: text formatters on text fields. It notifies about changes both when the input loses focus or when the user presses enter. You also can use them to provide additional restrictions on the input, e.g. restrict it to number only.

See [text formatters example](https://github.com/cljfx/cljfx/blob/master/examples/e29_text_formatter.clj).
