### ISSUE TITLE
menu-item doesn't accept a function as an on-action event handler

### ISSUE THREAD

**Issue by torkus** [cljfx/cljfx#89]
I have several menu components with many menu-item components and the only property they appear to have to attach a callback to is [onActionProperty](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/MenuItem.html#onActionProperty), however in cljfx using this component:

```clojure
{:fx/type :menu-item
 :text "some text"
 :on-action callback-fn}
```

I get this error:

    clojure.lang.ExceptionInfo: Don't know how to coerce {:target javafx.event.EventHandler, :x nil}

Which I think means ... a function can't be treated like an event handler, which seems strange. If I can't use a function then what do I use? (or am I using the wrong property?)

Cheers,

**Comment by vlaaad** [comment]
Hi! It says it can't coerce nil to event handler, perhaps your callback-fn is nil?

**Comment by torkus** [comment]
Ah, found it, sorry for the noise. I was half-asleep.
