### ISSUE TITLE
how to add table-view row class attributes

### ISSUE THREAD

**Issue by torkus** [cljfx/cljfx#92]
I need to add classes to certain rows in a table-view so I can style them differently. I have access to the cell factory for formatting cells by column, but not by row. row-factory appears to exist but doesn't accept a function like cell-factory does. Is this the right direction to be looking or am I missing something obvious?

**Comment by vlaaad** [comment]
Hi @torkus! I skipped it because I thought no one will ever need that, but I guess I was proven wrong :) I'll try adding support for that.

**Comment by torkus** [comment]
thanks, @vlaaad , it's appreciated. I've scoured the docs and the source code now and have tried many things that don't work.

The javafx docs even seem to dissuade you from touching TableRows:

> TableRow is an IndexedCell, but rarely needs to be used by developers creating TableView instances. The only time TableRow is likely to be encountered at all by a developer is if they wish to create a custom rowFactory that replaces an entire row of a TableView.

which makes me think I'm approaching this incorrectly. Right now I'm seeing if I can return an instance of `TableCell` instead of a map of data so I can attach a style class to it.

The Java solutions that I've seen on the internet seem [almost masochistic](https://rterp.wordpress.com/2015/04/11/atlas-trader-test/) but I'm almost tempted to try one just to test my interop skills.

**Comment by vlaaad** [comment]
Released [1.7.8](https://github.com/cljfx/cljfx/blob/master/CHANGELOG.md#178---2020-09-05): see `:row-factory` in [this example](https://github.com/cljfx/cljfx/blob/master/examples/e16_cell_factories.clj).

**Comment by torkus** [comment]
works a treat, thanks again.
